"""Auth wrapper around the generated AuthenticatedClient/Client.

Hand-maintained — NOT regenerated by `make sdks`. The drift gate explicitly
excludes this file via `:!sdks/python/geolens_sdk/auth.py` in the Makefile.

Backend auth precedence (matches `_resolve_api_key()` in
backend/app/modules/auth/dependencies.py):
    header X-API-Key  > JWT Bearer (Authorization)  > anonymous

The query-parameter `?api_key=<key>` fallback that the backend supports for
browser/embed contexts is NOT exposed by this SDK wrapper (D-11). Use one
of the two header modes via the constructor or the set_* helpers.
"""
from __future__ import annotations

from typing import Optional, Union

from .client import AuthenticatedClient, Client

__all__ = ["GeolensClient"]


class GeolensClient:
    """Single entry-point for the GeoLens Python SDK.

    Configure exactly one of bearer_token or api_key. With neither, the
    underlying client is anonymous and may only call public endpoints.

    Args:
        base_url: Base URL of the GeoLens instance, e.g. https://geolens.example.com
        bearer_token: JWT bearer token. Sent as `Authorization: Bearer <token>`.
        api_key: API key. Sent as `X-API-Key: <key>` (no prefix).

    Raises:
        ValueError: if both bearer_token and api_key are provided.

    Example:
        >>> from geolens_sdk import GeolensClient
        >>> from geolens_sdk.api.search import search_datasets_endpoint_search_datasets__get
        >>> c = GeolensClient(base_url="https://geolens.example.com", bearer_token="...")
        >>> resp = search_datasets_endpoint_search_datasets__get.sync_detailed(client=c.client)
    """

    def __init__(
        self,
        base_url: str,
        *,
        bearer_token: Optional[str] = None,
        api_key: Optional[str] = None,
    ) -> None:
        if bearer_token and api_key:
            raise ValueError(
                "Provide either bearer_token or api_key, not both."
            )
        self._base_url = base_url
        self._client: Union[AuthenticatedClient, Client]
        if bearer_token:
            self._client = AuthenticatedClient(
                base_url=base_url,
                token=bearer_token,
                # prefix defaults to "Bearer", auth_header_name to "Authorization"
            )
        elif api_key:
            self._client = AuthenticatedClient(
                base_url=base_url,
                token=api_key,
                prefix="",
                auth_header_name="X-API-Key",
            )
        else:
            self._client = Client(base_url=base_url)

    @property
    def client(self) -> Union[AuthenticatedClient, Client]:
        """Underlying generated client — pass to geolens_sdk.api.* functions."""
        return self._client

    def set_bearer_token(self, token: str) -> None:
        """Replace the underlying client with one configured for Bearer auth."""
        self._client = AuthenticatedClient(
            base_url=self._base_url,
            token=token,
        )

    def set_api_key(self, key: str) -> None:
        """Replace the underlying client with one configured for X-API-Key auth."""
        self._client = AuthenticatedClient(
            base_url=self._base_url,
            token=key,
            prefix="",
            auth_header_name="X-API-Key",
        )
