{{- if .Values.worker.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "geolens.fullname" . }}-worker
  labels:
    {{- include "geolens.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  minAvailable: {{ .Values.worker.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "geolens.worker.selectorLabels" . | nindent 6 }}
{{- end }}
