apiVersion: v1
kind: Service
metadata:
  name: {{ include "geolens.fullname" . }}-worker
  labels:
    {{- include "geolens.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  type: ClusterIP
  ports:
    - port: 8001
      targetPort: 8001
      protocol: TCP
      name: http
  selector:
    {{- include "geolens.worker.selectorLabels" . | nindent 4 }}
