{{- if .Values.api.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "geolens.fullname" . }}-api
  labels:
    {{- include "geolens.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
    {{- with .Values.api.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "geolens.api.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      interval: {{ .Values.api.serviceMonitor.interval | default "30s" }}
      path: /metrics
{{- end }}
