"""One backfill run must use one model resolution (#1519 review, P1).

`backfill.py` stamps every row it writes with a model name it resolved once,
but `generate_embeddings_batch` re-read `EMBEDDING_MODEL` for each provider
call. An admin switching models while a run is in flight therefore got vectors
generated by model B stored under label A. Search on active-B skips them, and a
switch back to A consumes vectors that model never produced.

The same argument applies to `EMBEDDING_DIMS`: pinning the model while the
dimensions still re-read would call the provider with model A and B's
dimensions, which is an inconsistency neither half had on its own.

This divergence predates #1519. On `origin/main`, `backfill.py:109` already
reads the label once before the batch loop while `service.py:79` re-reads per
call, and the non-force path carries it identically. The force guard widened
the window rather than opening it, which is why both paths are covered here.

The switch is driven through the real `PersistentConfig.set`, from inside
`resolve_runtime_config` — the one await that `service.py` makes *after*
backfill has resolved its label and *before* the service re-reads the config
for the provider call. That is the actual interleaving, not a stubbed input.

Requirements:
  - Docker database must be running (docker compose up db)
  - Alembic migrations must be applied
"""

import uuid
from types import SimpleNamespace

import pytest
from sqlalchemy import func, select

from app.core.persistent_config import EMBEDDING_DIMS, EMBEDDING_MODEL
from app.processing.embeddings import backfill as backfill_module
from app.processing.embeddings import service as service_module
from app.processing.embeddings.models import RecordEmbedding

from tests.factories import create_dataset, get_user_id

_MODEL_A = "pin-model-a"
_MODEL_B = "pin-model-b"
# 1536 matches the fixed vector column from migration 0012, so the row still
# inserts. The provider returns 1536 floats whatever it is told, which keeps
# the assertion on the argument it received rather than on what it returned.
_DIMS_A = 1536
_DIMS_B = 768


class _RecordingProvider:
    """Records the arguments each provider call received."""

    def __init__(self):
        self.calls: list[dict] = []

    async def resolve_runtime_config(self, session):
        return {
            "default_model": "provider-fallback-model",
            "default_dims": 1536,
            "base_url": "http://embeddings.invalid",
        }

    async def embed(self, *, texts, model, dimensions, base_url, timeout):
        self.calls.append({"model": model, "dimensions": dimensions})
        return [[1.0] + [0.0] * 1535 for _ in texts]


class _SwitchingProvider(_RecordingProvider):
    """Flips the live config from inside the provider call.

    `resolve_runtime_config` is the one await `service.py` makes after backfill
    has captured its own values and before the service would re-read them, so
    this covers the late window: a swap that lands once the run is already
    generating.
    """

    async def resolve_runtime_config(self, session):
        await EMBEDDING_MODEL.set(session, _MODEL_B)
        await EMBEDDING_DIMS.set(session, _DIMS_B)
        return await super().resolve_runtime_config(session)


async def _embedding_count(session) -> int:
    """Count every embedding row a force delete would clear."""
    return (
        await session.execute(select(func.count()).select_from(RecordEmbedding))
    ).scalar_one()


@pytest.fixture
async def restore_embedding_config(test_db_session):
    """Put EMBEDDING_MODEL/DIMS back; the worker DB is shared across tests."""
    before = (
        await EMBEDDING_MODEL.get(test_db_session),
        await EMBEDDING_DIMS.get(test_db_session),
    )
    yield
    await EMBEDDING_MODEL.set(test_db_session, before[0])
    await EMBEDDING_DIMS.set(test_db_session, before[1])


@pytest.mark.anyio
@pytest.mark.parametrize("force", [True, False], ids=["force", "non_force"])
async def test_a_mid_run_model_switch_cannot_mislabel_a_vector(
    test_db_session,
    monkeypatch,
    restore_embedding_config,
    force,
):
    """The label on a stored row must name the model that produced it."""
    user_id = await get_user_id(test_db_session, "admin")
    dataset = await create_dataset(
        test_db_session, created_by=user_id, name=f"Model Pinning {force}"
    )

    await EMBEDDING_MODEL.set(test_db_session, _MODEL_A)
    await EMBEDDING_DIMS.set(test_db_session, _DIMS_A)

    provider = _SwitchingProvider()
    monkeypatch.setattr(
        service_module, "get_embedding_provider", lambda _name: provider
    )
    monkeypatch.setattr(
        service_module, "settings", SimpleNamespace(openai_api_key="pin-test-key")
    )

    await backfill_module.backfill_embeddings(test_db_session, force=force)

    # Non-vacuity: with no provider call there is no argument to compare, and
    # with no stored row there is no label. Both would pass silently below.
    assert provider.calls, "the provider was never called"
    stored_label = (
        await test_db_session.execute(
            select(RecordEmbedding.model_name).where(
                RecordEmbedding.record_id == dataset.record_id
            )
        )
    ).scalar_one()

    call = provider.calls[0]
    # The finding itself: the row's label has to describe the vector in it.
    assert call["model"] == stored_label
    # And both halves have to come from the run's own resolution, not from
    # whatever the config happened to say by the time the provider was called.
    assert call["model"] == _MODEL_A
    assert call["dimensions"] == _DIMS_A


@pytest.mark.anyio
@pytest.mark.parametrize("force", [True, False], ids=["force", "non_force"])
async def test_a_switch_between_the_model_and_dims_reads_aborts_the_run(
    test_db_session,
    monkeypatch,
    restore_embedding_config,
    force,
):
    """A swap landing between the two capture reads must not pin a mixed pair.

    The earlier test flips the config once both values are already captured,
    so it is blind to the window *inside* the capture. The model and the
    dimensions come from separate `PersistentConfig` reads; a swap landing
    between them pins model A with model B's dimensions, a pairing that never
    existed in config. A provider that rejects it fails every insert, and one
    that accepts it writes vectors under a configuration nobody chose.

    The flip is hung on the dimensions read itself, which is the one call that
    sits between the two captures on both paths. It goes through the real
    `PersistentConfig.set`, and it fires once so the re-read observes the new
    value rather than flipping again underneath it.
    """
    user_id = await get_user_id(test_db_session, "admin")
    await create_dataset(
        test_db_session, created_by=user_id, name=f"Capture Window {force}"
    )
    await EMBEDDING_MODEL.set(test_db_session, _MODEL_A)
    await EMBEDDING_DIMS.set(test_db_session, _DIMS_A)

    # A row to lose. On the force path the snapshot sits ahead of the DELETE,
    # so an abort has to leave this untouched.
    seeded = await create_dataset(
        test_db_session, created_by=user_id, name=f"Capture Window Seed {force}"
    )
    test_db_session.add(
        RecordEmbedding(
            record_id=seeded.record_id,
            embedding=[1.0] + [0.0] * 1535,
            model_name=_MODEL_A,
            content_hash=uuid.uuid4().hex[:64],
        )
    )
    await test_db_session.commit()
    before = await _embedding_count(test_db_session)
    assert before > 0

    original_dims_get = EMBEDDING_DIMS.get
    flipped = False

    async def _flip_then_read(session):
        nonlocal flipped
        if not flipped:
            flipped = True
            await EMBEDDING_MODEL.set(session, _MODEL_B)
            await EMBEDDING_DIMS.set(session, _DIMS_B)
        return await original_dims_get(session)

    monkeypatch.setattr(EMBEDDING_DIMS, "get", _flip_then_read)

    provider = _RecordingProvider()
    monkeypatch.setattr(
        service_module, "get_embedding_provider", lambda _name: provider
    )
    monkeypatch.setattr(
        service_module, "settings", SimpleNamespace(openai_api_key="pin-test-key")
    )

    aborted = False
    try:
        await backfill_module.backfill_embeddings(test_db_session, force=force)
    except RuntimeError:
        aborted = True

    # Checked before the abort flag: an unfixed tree fails showing the mixed
    # pair it handed the provider, which is the damage, not the missing raise.
    assert provider.calls == []
    assert await _embedding_count(test_db_session) == before
    assert aborted
