"""One backfill run must use one model resolution (#1519 review, P1).

`backfill.py` stamps every row it writes with a model name it resolved once,
but `generate_embeddings_batch` re-read `EMBEDDING_MODEL` for each provider
call. An admin switching models while a run is in flight therefore got vectors
generated by model B stored under label A. Search on active-B skips them, and a
switch back to A consumes vectors that model never produced.

The same argument applies to `EMBEDDING_DIMS`: pinning the model while the
dimensions still re-read would call the provider with model A and B's
dimensions, which is an inconsistency neither half had on its own.

This divergence predates #1519. On `origin/main`, `backfill.py:109` already
reads the label once before the batch loop while `service.py:79` re-reads per
call, and the non-force path carries it identically. The force guard widened
the window rather than opening it, which is why both paths are covered here.

The switch is driven through the real `PersistentConfig.set`, from inside
`resolve_runtime_config` — the one await that `service.py` makes *after*
backfill has resolved its label and *before* the service re-reads the config
for the provider call. That is the actual interleaving, not a stubbed input.

Requirements:
  - Docker database must be running (docker compose up db)
  - Alembic migrations must be applied
"""

import uuid
from types import SimpleNamespace
from unittest.mock import AsyncMock, MagicMock

import pytest
from sqlalchemy import func, select, text

from app.core.persistent_config import EMBEDDING_DIMS, EMBEDDING_MODEL
from app.processing.embeddings import backfill as backfill_module
from app.processing.embeddings import service as service_module
from app.processing.embeddings.models import RecordEmbedding
from app.processing.embeddings.service import EmbeddingUnavailableError

from tests.factories import create_dataset, get_user_id

_MODEL_A = "pin-model-a"
_MODEL_B = "pin-model-b"
# 1536 matches the fixed vector column from migration 0012, so the row still
# inserts. The provider returns 1536 floats whatever it is told, which keeps
# the assertion on the argument it received rather than on what it returned.
_DIMS_A = 1536
_DIMS_B = 768


class _RecordingProvider:
    """Records the arguments each provider call received."""

    def __init__(self):
        self.calls: list[dict] = []
        # Stashed for the subclass that has to write config from inside a
        # provider call; `embed` is not handed a session.
        self._session = None

    async def resolve_runtime_config(self, session):
        self._session = session
        return {
            "default_model": "provider-fallback-model",
            "default_dims": 1536,
            "base_url": "http://embeddings.invalid",
        }

    async def embed(self, *, texts, model, dimensions, base_url, timeout):
        self.calls.append({"model": model, "dimensions": dimensions})
        return [[1.0] + [0.0] * 1535 for _ in texts]


class _StrictProvider(_RecordingProvider):
    """Rejects a (model, dimensions) pair the model does not support.

    Real embedding endpoints do this: asking a 768-dimension model for 1536
    is an error, not a silently truncated vector. Without that, a fake
    provider would happily accept the mismatched pair and the scenario would
    prove nothing.
    """

    _SUPPORTED = {_MODEL_A: _DIMS_A, _MODEL_B: _DIMS_B}

    async def embed(self, *, texts, model, dimensions, base_url, timeout):
        self.calls.append({"model": model, "dimensions": dimensions})
        if self._SUPPORTED.get(model) != dimensions:
            raise EmbeddingUnavailableError(
                f"model {model} does not support {dimensions} dimensions"
            )
        return [[1.0] + [0.0] * 1535 for _ in texts]


class _WidthProvider(_RecordingProvider):
    """Returns vectors of the width it was asked for.

    `_RecordingProvider` always answers 1536 regardless of `dimensions`, which
    is fine for the labelling scenarios but cannot express "the provider
    succeeded and the result does not fit the column". A real endpoint asked
    for 768 returns 768.
    """

    async def embed(self, *, texts, model, dimensions, base_url, timeout):
        self.calls.append({"model": model, "dimensions": dimensions})
        width = dimensions or 1536
        return [[1.0] + [0.0] * (width - 1) for _ in texts]


class _ExplodingProvider(_RecordingProvider):
    """Fails every call, so needing the provider at all is observable."""

    async def embed(self, *, texts, model, dimensions, base_url, timeout):
        self.calls.append({"model": model, "dimensions": dimensions})
        raise EmbeddingUnavailableError("no provider configured")


class _SwitchingProvider(_RecordingProvider):
    """Flips the live config from inside the first provider call.

    Covers the late window: a swap that lands once the run is already
    generating, after the snapshot has captured its own values and before the
    service would re-read them.

    The flip hangs on `embed` rather than on `resolve_runtime_config`, which is
    where it used to sit. fix(#1525) made `_snapshot_embedding_config` resolve
    the endpoint through `resolve_runtime_config`, so a flip there now lands
    INSIDE the capture window and the snapshot's comparison aborts the run.
    That is a real behaviour and it has its own coverage
    (`test_an_edit_inside_the_snapshot_window_aborts_the_run`), but it is not
    the scenario this file is about. `embed` is the first await after the
    snapshot completes on both paths, and it is where a run actually spends its
    time, so it is the more faithful place for an admin edit to land.
    """

    def __init__(self):
        super().__init__()
        self._switched = False

    async def embed(self, *, texts, model, dimensions, base_url, timeout):
        vectors = await super().embed(
            texts=texts,
            model=model,
            dimensions=dimensions,
            base_url=base_url,
            timeout=timeout,
        )
        if not self._switched:
            self._switched = True
            await EMBEDDING_MODEL.set(self._session, _MODEL_B)
            await EMBEDDING_DIMS.set(self._session, _DIMS_B)
        return vectors


async def _embedding_count(session) -> int:
    """Count every embedding row a force delete would clear."""
    return (
        await session.execute(select(func.count()).select_from(RecordEmbedding))
    ).scalar_one()


@pytest.fixture
async def restore_embedding_config(test_db_session):
    """Put EMBEDDING_MODEL/DIMS back; the worker DB is shared across tests."""
    before = (
        await EMBEDDING_MODEL.get(test_db_session),
        await EMBEDDING_DIMS.get(test_db_session),
    )
    yield
    await EMBEDDING_MODEL.set(test_db_session, before[0])
    await EMBEDDING_DIMS.set(test_db_session, before[1])


@pytest.mark.anyio
@pytest.mark.parametrize("force", [True, False], ids=["force", "non_force"])
async def test_a_mid_run_model_switch_cannot_mislabel_a_vector(
    test_db_session,
    monkeypatch,
    restore_embedding_config,
    force,
):
    """The label on a stored row must name the model that produced it."""
    user_id = await get_user_id(test_db_session, "admin")
    dataset = await create_dataset(
        test_db_session, created_by=user_id, name=f"Model Pinning {force}"
    )
    # A second record, so the non-force path always has work for a second
    # batch. It selects only records with no vector under the ACTIVE model, and
    # a sibling run that already embedded the catalog under _MODEL_A leaves
    # exactly one: this test's own new dataset. One call is one call too few to
    # catch a swap that lands during the first.
    await create_dataset(
        test_db_session, created_by=user_id, name=f"Model Pinning Second {force}"
    )

    await EMBEDDING_MODEL.set(test_db_session, _MODEL_A)
    await EMBEDDING_DIMS.set(test_db_session, _DIMS_A)

    provider = _SwitchingProvider()
    monkeypatch.setattr(
        service_module, "get_embedding_provider", lambda _name: provider
    )
    monkeypatch.setattr(
        service_module, "settings", SimpleNamespace(openai_api_key="pin-test-key")
    )
    # One record per provider call. The swap lands during the first call, so
    # the run needs a second one for it to be in front of; at the default batch
    # size of 128 the non-force path makes exactly one and the assertions below
    # would hold on an unpinned tree too.
    monkeypatch.setattr(backfill_module, "_BATCH_SIZE", 1)

    await backfill_module.backfill_embeddings(test_db_session, force=force)

    # Non-vacuity: with fewer than two provider calls there is no post-swap call
    # to catch, and with no stored row there is no label. Both would pass
    # silently below.
    assert len(provider.calls) >= 2, "the run made fewer than two provider calls"
    assert await EMBEDDING_MODEL.get(test_db_session) == _MODEL_B, (
        "the admin swap never landed"
    )
    stored_label = (
        await test_db_session.execute(
            select(RecordEmbedding.model_name).where(
                RecordEmbedding.record_id == dataset.record_id
            )
        )
    ).scalar_one()

    # The finding itself: the row's label has to describe the vector in it, and
    # EVERY call has to agree, not just the one before the swap.
    assert {call["model"] for call in provider.calls} == {stored_label}
    # And both halves have to come from the run's own resolution, not from
    # whatever the config happened to say by the time the provider was called.
    assert {call["model"] for call in provider.calls} == {_MODEL_A}
    assert {call["dimensions"] for call in provider.calls} == {_DIMS_A}


@pytest.mark.anyio
@pytest.mark.parametrize("force", [True, False], ids=["force", "non_force"])
async def test_a_switch_between_the_model_and_dims_reads_aborts_the_run(
    test_db_session,
    monkeypatch,
    restore_embedding_config,
    force,
):
    """A swap landing between the two capture reads must not pin a mixed pair.

    The earlier test flips the config once both values are already captured,
    so it is blind to the window *inside* the capture. The model and the
    dimensions come from separate `PersistentConfig` reads; a swap landing
    between them pins model A with model B's dimensions, a pairing that never
    existed in config. A provider that rejects it fails every insert, and one
    that accepts it writes vectors under a configuration nobody chose.

    The flip is hung on the dimensions read itself, which is the one call that
    sits between the two captures on both paths. It goes through the real
    `PersistentConfig.set`, and it fires once so the re-read observes the new
    value rather than flipping again underneath it.
    """
    user_id = await get_user_id(test_db_session, "admin")
    await create_dataset(
        test_db_session, created_by=user_id, name=f"Capture Window {force}"
    )
    await EMBEDDING_MODEL.set(test_db_session, _MODEL_A)
    await EMBEDDING_DIMS.set(test_db_session, _DIMS_A)

    # A row to lose. On the force path the snapshot sits ahead of the DELETE,
    # so an abort has to leave this untouched.
    seeded = await create_dataset(
        test_db_session, created_by=user_id, name=f"Capture Window Seed {force}"
    )
    test_db_session.add(
        RecordEmbedding(
            record_id=seeded.record_id,
            embedding=[1.0] + [0.0] * 1535,
            model_name=_MODEL_A,
            content_hash=uuid.uuid4().hex[:64],
        )
    )
    await test_db_session.commit()
    before = await _embedding_count(test_db_session)
    assert before > 0

    # fix(#1525 review r2): hung on the UNCACHED read, which is the one the
    # snapshot makes now. The cached read is still what everything else uses, so
    # both are patched and the flip fires on whichever the snapshot reaches
    # first — the point is that it lands between the two captures, not which
    # layer serves them.
    original_dims_get = EMBEDDING_DIMS.get
    original_dims_get_uncached = EMBEDDING_DIMS.get_uncached
    flipped = False

    async def _flip(session) -> None:
        nonlocal flipped
        if not flipped:
            flipped = True
            await EMBEDDING_MODEL.set(session, _MODEL_B)
            await EMBEDDING_DIMS.set(session, _DIMS_B)

    async def _flip_then_read(session):
        await _flip(session)
        return await original_dims_get(session)

    async def _flip_then_read_uncached(session):
        await _flip(session)
        return await original_dims_get_uncached(session)

    monkeypatch.setattr(EMBEDDING_DIMS, "get", _flip_then_read)
    monkeypatch.setattr(EMBEDDING_DIMS, "get_uncached", _flip_then_read_uncached)

    provider = _RecordingProvider()
    monkeypatch.setattr(
        service_module, "get_embedding_provider", lambda _name: provider
    )
    monkeypatch.setattr(
        service_module, "settings", SimpleNamespace(openai_api_key="pin-test-key")
    )

    aborted = False
    try:
        await backfill_module.backfill_embeddings(test_db_session, force=force)
    except RuntimeError:
        aborted = True

    # Checked before the abort flag: an unfixed tree fails showing the mixed
    # pair it handed the provider, which is the damage, not the missing raise.
    assert provider.calls == []
    assert await _embedding_count(test_db_session) == before
    assert aborted


@pytest.mark.anyio
async def test_a_model_published_before_its_dimensions_does_not_destroy_vectors(
    test_db_session,
    monkeypatch,
    restore_embedding_config,
):
    """The settings window: a committed, stable, mismatched pair.

    `update_settings` commits a new `embedding_model` and only then awaits the
    external dimension probe (`settings/router.py`), so for the length of that
    probe the stored pair is the new model with the old dimensions. It is
    committed and it is stable, so re-reading it agrees with itself and learns
    nothing. No comparison-based guard can see this one.

    That window opens the moment an admin switches models, which is the moment
    someone clicks Regenerate All. This is the sequence the whole issue is
    about, reached through the door the guards do not cover.

    The pre-flight catches it by not reasoning about it at all: it asks the
    provider for one vector using the live configuration, and the provider
    rejects the pair.
    """
    user_id = await get_user_id(test_db_session, "admin")
    await create_dataset(test_db_session, created_by=user_id, name="Settings Window")

    await EMBEDDING_MODEL.set(test_db_session, _MODEL_A)
    await EMBEDDING_DIMS.set(test_db_session, _DIMS_A)

    seeded = await create_dataset(
        test_db_session, created_by=user_id, name="Settings Window Seed"
    )
    test_db_session.add(
        RecordEmbedding(
            record_id=seeded.record_id,
            embedding=[1.0] + [0.0] * 1535,
            model_name=_MODEL_A,
            content_hash=uuid.uuid4().hex[:64],
        )
    )
    await test_db_session.commit()
    before = await _embedding_count(test_db_session)
    assert before > 0

    # The intermediate state itself: model B published, dimensions still A's.
    # Nothing is racing after this line; the pair simply sits there wrong.
    await EMBEDDING_MODEL.set(test_db_session, _MODEL_B)
    assert await EMBEDDING_MODEL.get(test_db_session) == _MODEL_B
    assert await EMBEDDING_DIMS.get(test_db_session) == _DIMS_A

    provider = _StrictProvider()
    monkeypatch.setattr(
        service_module, "get_embedding_provider", lambda _name: provider
    )
    monkeypatch.setattr(
        service_module, "settings", SimpleNamespace(openai_api_key="pin-test-key")
    )

    aborted = False
    try:
        await backfill_module.backfill_embeddings(test_db_session, force=True)
    except RuntimeError:
        aborted = True

    # Survival first: an unguarded tree fails on the vectors it destroyed.
    assert await _embedding_count(test_db_session) == before
    assert aborted
    # The pre-flight has to have actually reached the provider. A pre-flight
    # that quietly no-ops would satisfy both assertions above while proving
    # nothing, since this run aborts either way.
    assert provider.calls == [{"model": _MODEL_B, "dimensions": _DIMS_A}]


@pytest.mark.anyio
async def test_a_generated_vector_that_cannot_be_stored_does_not_destroy_vectors(
    test_db_session,
    monkeypatch,
    restore_embedding_config,
):
    """Generating is only half the promise: the vector has to fit the column.

    fix(#1511 review r4, codex P1): the width a model produces and the width
    the column declares are written by different code at different times, so
    they can disagree. What found it was a settings write that persisted a
    newly detected width without rebuilding the column, leaving storage at the
    old one (that path is the subject of #1529).

    The scenario below is built from the mismatch itself rather than from that
    route: a model whose vectors are the wrong width for the live column. It
    therefore holds whatever produced the mismatch, which is the point of the
    guard it covers — that guard reads storage, not config, so closing any one
    route does not retire it.

    Every earlier guard passes here, and that is the point. Model and
    dimensions are consistent with each other, they are stable, and the
    provider answers happily at the new width. Only storage disagrees, and it
    is the one thing no config check looks at.

    Against a tree without the storage half of the pre-flight this fails on the
    survival assertion, not on the missing raise: the DELETE commits and every
    replacement insert dies on the typmod.
    """
    user_id = await get_user_id(test_db_session, "admin")

    column_dims = (
        await test_db_session.execute(
            text(
                "SELECT atttypmod FROM pg_attribute "
                "WHERE attrelid = 'catalog.record_embeddings'::regclass "
                "AND attname = 'embedding' AND NOT attisdropped"
            )
        )
    ).scalar_one()
    # Non-vacuity: an unconstrained `vector` column (atttypmod -1) accepts any
    # width, so there would be no mismatch to detect and the test would assert
    # nothing. The scenario needs a declared width that is NOT what the model
    # produces.
    assert column_dims > 0
    assert column_dims != _DIMS_B

    seeded = await create_dataset(
        test_db_session, created_by=user_id, name="Storage Width Seed"
    )
    test_db_session.add(
        RecordEmbedding(
            record_id=seeded.record_id,
            embedding=[1.0] + [0.0] * (column_dims - 1),
            model_name=_MODEL_A,
            content_hash=uuid.uuid4().hex[:64],
        )
    )
    await test_db_session.commit()
    before = await _embedding_count(test_db_session)
    assert before > 0

    # A *consistent* pair, unlike the settings-window scenario: the model and
    # its dimensions agree, so the snapshot and re-read guards are satisfied.
    await EMBEDDING_MODEL.set(test_db_session, _MODEL_B)
    await EMBEDDING_DIMS.set(test_db_session, _DIMS_B)

    provider = _WidthProvider()
    monkeypatch.setattr(
        service_module, "get_embedding_provider", lambda _name: provider
    )
    monkeypatch.setattr(
        service_module, "settings", SimpleNamespace(openai_api_key="pin-test-key")
    )

    aborted = False
    try:
        await backfill_module.backfill_embeddings(test_db_session, force=True)
    except RuntimeError:
        aborted = True

    assert await _embedding_count(test_db_session) == before
    assert aborted
    # The provider must have been reached and must have succeeded — if it had
    # rejected the pair this would be the round-3 scenario over again, and the
    # storage check would never have been the thing that saved the vectors.
    assert provider.calls == [{"model": _MODEL_B, "dimensions": _DIMS_B}]


@pytest.mark.anyio
async def test_force_on_an_empty_catalog_does_not_need_a_working_provider():
    """Nothing at risk means nothing to guard.

    fix(#1511 review r5, codex P2): the force guards exist to protect rows from
    the DELETE, and that DELETE is bounded by the record foreign key. A tenant
    with no visible records cannot lose one, so demanding a working provider
    just to discover that turned a harmless no-op into a 502 on a fresh
    install.

    Driven through a mock session — the same shape
    `test_admin_stats_and_force_delete_are_record_scoped` uses for this path —
    because "the catalog is empty" is not a state the shared worker DB can be
    held in: sibling tests create datasets, and an emptiness assertion against
    the real session passes alone and fails in a suite.

    The provider raises on any call, which is what makes this mean something:
    on a tree that pre-flights before checking, the run aborts instead.
    """
    empty_result = MagicMock()
    empty_result.first.return_value = None
    session = AsyncMock()
    session.execute.return_value = empty_result

    port = SimpleNamespace(
        get_record_orm_class=lambda: SimpleNamespace(id=RecordEmbedding.record_id),
        get_records_without_embeddings=AsyncMock(
            side_effect=AssertionError(
                "the force path kept going after finding no visible records"
            )
        ),
    )

    provider = _ExplodingProvider()
    with pytest.MonkeyPatch.context() as mp:
        mp.setattr(backfill_module, "get_processing_port", lambda: port)
        mp.setattr(service_module, "get_embedding_provider", lambda _name: provider)
        mp.setattr(
            service_module, "settings", SimpleNamespace(openai_api_key="pin-test-key")
        )
        result = await backfill_module.backfill_embeddings(session, force=True)

    assert result == {"processed": 0, "created": 0, "skipped": 0, "errors": 0}
    # Non-vacuity: surviving the run is not the claim — never needing the
    # provider is. Reintroducing the call would raise before this line, so
    # assert the absence rather than relying on the run having completed.
    assert provider.calls == []
    # And nothing was deleted or committed on the way to that answer.
    session.commit.assert_not_awaited()
