"""Byte-identity harness for the #1089 split of ``app.platform.analysis_sql``.

THROWAWAY. This file exists to prove one thing about one commit range: that
carving ``analysis_sql`` into per-family modules moved code without changing a
single rendered character. Once the split has landed and been reviewed it has
served its purpose and should be deleted — it pins the CURRENT text of every
statement, so any later PR that legitimately changes SQL would have to update
the fixture, which is busywork that teaches a future reader nothing.

How it proves it. ``tests/fixtures/analysis_sql_pre_split_1089.json`` was
generated by running ``render_all()`` and ``surface()`` below against the
PRE-SPLIT module, at the commit that added this file — so the expected side is
output that actually ran, not strings transcribed by hand. After the carve the
same two functions run against the façade and must agree exactly.

Two properties, because the two ways this refactor can go wrong are different:

- every rendered statement is byte-identical (a moved renderer that picked up
  a different constant, or a re-indented f-string, shows up here);
- no symbol the pre-split module DEFINED disappeared from the façade (a
  re-export left out of ``__init__`` breaks a caller at import time, and the
  callers are deliberately untouched by this PR so nothing else would catch it).
"""

from __future__ import annotations

import ast
import json
from pathlib import Path
from typing import Any

import pytest

from app.platform import analysis_sql

_FIXTURE = Path(__file__).parent / "fixtures" / "analysis_sql_pre_split_1089.json"

# Names that were module attributes of the pre-split analysis_sql.py only
# because it imported them at the top of a single file. They are not API: no
# caller imports them from analysis_sql (verified by grep over backend/), and a
# package façade has no reason to re-export the stdlib. Listed rather than
# filtered by a heuristic so the reconciliation is reviewable.
_IMPORT_ARTIFACTS = frozenset(
    {
        "Any",
        "GEOSException",
        "LON_EPSILON_DEGREES",
        "Sequence",
        "annotations",
        "math",
        "re",
        "shape",
        "shapely",
    }
)

_MASK: dict[str, Any] = {
    "type": "Polygon",
    "coordinates": [[[0.0, 0.0], [1.0, 0.0], [1.0, 1.0], [0.0, 1.0], [0.0, 0.0]]],
}
_MULTI_MASK: dict[str, Any] = {
    "type": "MultiPolygon",
    "coordinates": [
        [[[0.0, 0.0], [1.0, 0.0], [1.0, 1.0], [0.0, 1.0], [0.0, 0.0]]],
        [[[5.0, 5.0], [6.0, 5.0], [6.0, 6.0], [5.0, 6.0], [5.0, 5.0]]],
    ],
}
# A bowtie: invalid as given, so it exercises the shapely make_valid branch.
_BOWTIE_MASK: dict[str, Any] = {
    "type": "Polygon",
    "coordinates": [[[0.0, 0.0], [2.0, 2.0], [2.0, 0.0], [0.0, 2.0], [0.0, 0.0]]],
}

_SRC = 'public."ds_1"'
_MASK_TABLE = 'public."ds_2"'
_JOIN_TABLE = 'public."ds_3"'


def _err(fn: Any, *args: Any, **kwargs: Any) -> str:
    """Render a validation failure as text, so error paths are pinned too."""
    try:
        fn(*args, **kwargs)
    except Exception as exc:  # noqa: BLE001 - the message IS the fixture value
        return f"{type(exc).__name__}: {exc}"
    return "<no error>"


def render_all() -> dict[str, str]:
    """Every statement this module can render, keyed by case name."""
    m = analysis_sql
    cases: dict[str, str] = {}

    # --- constants ------------------------------------------------------
    for name in (
        "BUFFER_LOCAL_SRID_SPAN_DEG",
        "BUFFER_SLICE_SEGMENTIZE_M",
        "BUFFER_SLICE_SEGMENTIZE_PLANAR_DEG",
        "DATELINE_WRAP_SPAN_DEG",
        "INTERNAL_ALIAS_PREFIX",
        "INTERSECT_OUTPUT_COLUMNS",
        "INTERSECT_SOURCE_GID_COLUMN",
        "LATERAL_ALIAS",
        "MASK_SUBDIVIDE_MAX_VERTICES",
        "MAX_BUFFER_METERS",
        "MAX_IDENTIFIER_LENGTH",
        "MAX_MASK_LAYER_FEATURES",
        "MAX_MASK_VERTICES",
        "MAX_SOURCE_FEATURES",
        "MAX_SPATIAL_JOIN_FIELDS",
        "MEASURE_AREA_COLUMN",
        "MEASURE_LENGTH_COLUMN",
        "MEASURE_OUTPUT_COLUMNS",
        "NON_GROUPABLE_COLUMN_TYPES",
        "NOT_EMPTY_PREDICATE",
        "SPATIAL_JOIN_COUNT_COLUMN",
        "SPATIAL_JOIN_FIELD_PREFIX",
    ):
        value = getattr(m, name)
        if isinstance(value, (dict, frozenset, set)):
            value = sorted(value.items()) if isinstance(value, dict) else sorted(value)
        cases[f"const/{name}"] = repr(value)

    # --- antimeridian helper --------------------------------------------
    cases["dateline/default"] = m.render_dateline_safe("geom_4326")
    cases["dateline/aliased"] = m.render_dateline_safe(
        "ST_MakeValid(geom_4326)", alias="_zz"
    )

    # --- transform -------------------------------------------------------
    # The default alias is load-bearing: platform/sandbox/validator.py
    # re-renders this template and compares (fix(#1001)).
    cases["buffer/default_alias"] = m.render_geodesic_buffer(
        "ST_MakeValid(geom_4326)", 1000.0
    )
    cases["buffer/custom_alias"] = m.render_geodesic_buffer("geom", 25.5, alias="_bb")
    cases["buffer/integral_distance"] = m.render_geodesic_buffer("geom_4326", 100)
    cases["buffer/max_distance"] = m.render_geodesic_buffer(
        "geom_4326", m.MAX_BUFFER_METERS
    )

    # --- overlay: clip against a mask LAYER -------------------------------
    for i, part in enumerate(m.render_clip_layer_join(_MASK_TABLE, src="_src")):
        cases[f"clip_layer_join/part{i}"] = part
    for i, part in enumerate(m.render_clip_layer_join(_MASK_TABLE, src="t")):
        cases[f"clip_layer_join_alt_src/part{i}"] = part

    # --- overlay: intersect ----------------------------------------------
    cases["intersect_pairs/bare"] = m.render_intersect_pairs(_SRC, _MASK_TABLE)
    cases["intersect_pairs/src_cols"] = m.render_intersect_pairs(
        _SRC, _MASK_TABLE, src_columns=('"name"', '"area"')
    )
    cases["intersect_pairs/mask_cols"] = m.render_intersect_pairs(
        _SRC, _MASK_TABLE, mask_columns=('"zone"',)
    )
    cases["intersect_pairs/both_cols"] = m.render_intersect_pairs(
        _SRC, _MASK_TABLE, src_columns=('"name"',), mask_columns=('"zone"', '"risk"')
    )
    cases["intersect_preview/p6"] = m.render_intersect_preview(
        _SRC, _MASK_TABLE, geojson_precision=6
    )
    cases["intersect_preview/p9"] = m.render_intersect_preview(
        _SRC, _MASK_TABLE, geojson_precision=9
    )

    # --- overlay: select by location --------------------------------------
    cases["sbl_where/src"] = m.render_select_by_location_where(_MASK_TABLE, src="_src")
    cases["sbl_where/alt_src"] = m.render_select_by_location_where(_MASK_TABLE, src="q")
    cases["sbl_count/layer"] = m.render_select_by_location_count(
        _SRC, mask_table_ref=_MASK_TABLE, mask=None
    )
    cases["sbl_count/drawn"] = m.render_select_by_location_count(
        _SRC, mask_table_ref=None, mask=_MASK
    )
    cases["sbl_count/drawn_multi"] = m.render_select_by_location_count(
        _SRC, mask_table_ref=None, mask=_MULTI_MASK
    )

    # --- measure -----------------------------------------------------------
    for i, part in enumerate(m.render_measure_columns()):
        cases[f"measure_columns/unqualified/part{i}"] = part
    for i, part in enumerate(m.render_measure_columns(src="_src")):
        cases[f"measure_columns/qualified/part{i}"] = part

    # --- spatial join ------------------------------------------------------
    cases["sj_output_columns/none"] = repr(m.spatial_join_output_columns(None))
    cases["sj_output_columns/empty"] = repr(m.spatial_join_output_columns([]))
    cases["sj_output_columns/fields"] = repr(
        m.spatial_join_output_columns(["name", "pop"])
    )
    cases["sj_output_columns/overlong"] = repr(
        m.spatial_join_output_columns(["f" * 80, "g" * 58 + "abcdef"])
    )
    for i, part in enumerate(m.render_spatial_join(_JOIN_TABLE, src="_src")):
        cases[f"spatial_join/no_fields/part{i}"] = part
    for i, part in enumerate(
        m.render_spatial_join(_JOIN_TABLE, src="_src", join_fields=["name"])
    ):
        cases[f"spatial_join/one_field/part{i}"] = part
    for i, part in enumerate(
        m.render_spatial_join(_JOIN_TABLE, src="t", join_fields=["name", "pop_est"])
    ):
        cases[f"spatial_join/two_fields/part{i}"] = part
    cases["sj_match_count/default"] = m.render_spatial_join_match_count(
        _SRC, _JOIN_TABLE
    )

    # --- mask parsing (the injection boundary) -----------------------------
    cases["mask_expr/polygon"] = m.render_mask_expr(_MASK)
    cases["mask_expr/multipolygon"] = m.render_mask_expr(_MULTI_MASK)
    cases["mask_expr/repaired_bowtie"] = m.render_mask_expr(_BOWTIE_MASK)

    # --- the per-row dispatcher -------------------------------------------
    dispatch: list[tuple[str, dict[str, Any]]] = [
        ("buffer", {"distance_meters": 500.0}),
        ("buffer", {"distance_meters": 1}),
        ("centroid", {}),
        ("measure", {}),
        ("spatial_join", {}),
        ("select_by_location", {"mask": _MASK}),
        ("select_by_location", {"mask": _MULTI_MASK}),
        ("clip", {"mask": _MASK}),
        ("clip", {"mask": _MULTI_MASK}),
    ]
    for op, kwargs in dispatch:
        tag = "+".join(f"{k}={v!r}" for k, v in sorted(kwargs.items())) or "bare"
        expr, where = m.render_geometry_expr(op, **kwargs)
        cases[f"geometry_expr/{op}/{tag}/expr"] = expr
        cases[f"geometry_expr/{op}/{tag}/where"] = where

    # --- validation failures ----------------------------------------------
    cases["err/mask/not_a_geometry"] = _err(m.render_mask_expr, {"type": "Nope"})
    cases["err/mask/point"] = _err(
        m.render_mask_expr, {"type": "Point", "coordinates": [0, 0]}
    )
    cases["err/mask/empty"] = _err(
        m.render_mask_expr, {"type": "Polygon", "coordinates": []}
    )
    cases["err/mask/nonfinite"] = _err(
        m.render_mask_expr,
        {
            "type": "Polygon",
            "coordinates": [
                [
                    [0.0, 0.0],
                    [float("inf"), 0.0],
                    [1.0, 1.0],
                    [0.0, 0.0],
                ]
            ],
        },
    )
    cases["err/mask/too_many_vertices"] = _err(
        m.render_mask_expr,
        {
            "type": "Polygon",
            "coordinates": [
                [[float(i % 90), float(i % 45)] for i in range(m.MAX_MASK_VERTICES + 2)]
                + [[0.0, 0.0]]
            ],
        },
    )
    cases["err/buffer/missing_distance"] = _err(m.render_geometry_expr, "buffer")
    cases["err/buffer/zero"] = _err(
        m.render_geometry_expr, "buffer", distance_meters=0.0
    )
    cases["err/buffer/over_max"] = _err(
        m.render_geometry_expr, "buffer", distance_meters=m.MAX_BUFFER_METERS + 1
    )
    cases["err/buffer/nan"] = _err(
        m.render_geometry_expr, "buffer", distance_meters=float("nan")
    )
    cases["err/dispatch/unsupported"] = _err(m.render_geometry_expr, "explode")
    cases["err/sj/duplicate_fields"] = _err(
        m.render_spatial_join, _JOIN_TABLE, src="_src", join_fields=["a", "a"]
    )
    cases["err/sj/too_many_fields"] = _err(
        m.render_spatial_join,
        _JOIN_TABLE,
        src="_src",
        join_fields=[f"f{i}" for i in range(m.MAX_SPATIAL_JOIN_FIELDS + 1)],
    )
    cases["err/sj/bad_field_name"] = _err(
        m.render_spatial_join, _JOIN_TABLE, src="_src", join_fields=['a"b']
    )
    return cases


def surface() -> dict[str, list[str]]:
    """The importable names, split into what the module DEFINES and the rest."""
    source = Path(analysis_sql.__file__).read_text(encoding="utf-8")
    defined: set[str] = set()
    for node in ast.parse(source).body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            defined.add(node.name)
        elif isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name):
                    defined.add(target.id)
        elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            defined.add(node.target.id)
    return {
        "defined": sorted(n for n in defined if not n.startswith("_")),
        "dir_public": sorted(n for n in dir(analysis_sql) if not n.startswith("_")),
    }


def _expected() -> dict[str, Any]:
    if not _FIXTURE.exists():  # pragma: no cover - generation bootstrap only
        pytest.fail(
            f"{_FIXTURE} is missing. It must be generated from the PRE-SPLIT "
            "module; regenerating it from post-split code proves nothing."
        )
    return json.loads(_FIXTURE.read_text(encoding="utf-8"))


@pytest.mark.architecture
def test_every_rendered_statement_is_byte_identical_across_the_split() -> None:
    """No character of any rendered statement changed. #1089 is a move."""
    expected = _expected()["rendered"]
    actual = render_all()

    assert sorted(actual) == sorted(expected), (
        "the case set itself changed; the fixture and the harness must cover "
        "the same statements for the comparison to mean anything"
    )
    drift = [k for k in sorted(expected) if expected[k] != actual[k]]
    if drift:
        first = drift[0]
        pytest.fail(
            f"{len(drift)} rendered statement(s) changed across the split, which "
            f"#1089 forbids — it is a move, not an SQL change.\n"
            f"First: {first}\n  before: {expected[first]!r}\n  after:  {actual[first]!r}"
        )


@pytest.mark.architecture
def test_the_facade_drops_no_symbol_the_pre_split_module_defined() -> None:
    """Every name the single file defined is still importable from the façade.

    The callers (``service_analysis.py``, ``tasks.py``, ``router_analysis.py``,
    ``schemas.py``, the sandbox validator, the NL->SQL prompt) are deliberately
    untouched by this PR, so a re-export left out of ``__init__`` surfaces as an
    ImportError in whichever suite happens to import that caller first. This
    fails on the façade instead, naming the symbol.
    """
    expected = _expected()["surface"]
    now = surface()

    missing = sorted(set(expected["defined"]) - set(dir(analysis_sql)))
    assert not missing, (
        "the façade no longer exports these names, which the pre-split module "
        f"defined: {missing}"
    )

    # Everything else that stopped being importable must be an import artifact
    # of the old single file, not API.
    lost = set(expected["dir_public"]) - set(now["dir_public"])
    assert lost <= _IMPORT_ARTIFACTS, (
        "the façade dropped importable names that are not stdlib/third-party "
        f"import artifacts: {sorted(lost - _IMPORT_ARTIFACTS)}"
    )
