// SPDX-License-Identifier: Apache-2.0
/**
 * Auth wrapper for the GeoLens TypeScript SDK.
 *
 * Hand-maintained — NOT regenerated by `make sdks`. The drift gate
 * explicitly excludes this file via `:!sdks/typescript/src/auth.ts` in
 * the Makefile.
 *
 * Backend auth precedence (matches `_resolve_api_key()` in
 * backend/app/modules/auth/dependencies.py):
 *     header X-API-Key  >  JWT Bearer (Authorization)  >  anonymous
 *
 * The query-parameter `?api_key=<key>` fallback that the backend supports
 * for browser/embed contexts is NOT exposed by this SDK wrapper (D-11).
 */
import { createClient, createConfig, type Client } from './client/client/index.js';

export interface GeolensClientOptions {
  /**
   * Base URL of the GeoLens instance, including the `/api` prefix the
   * deployed API is served under, e.g. https://geolens.example.com/api
   */
  baseUrl: string;
  /** JWT bearer token. Sent as `Authorization: Bearer <token>`. */
  bearerToken?: string;
  /** API key. Sent as `X-API-Key: <key>` (no prefix). */
  apiKey?: string;
}

export interface GeolensClient {
  /** The configured base URL. */
  baseUrl: string;
  /** The headers used for every request. */
  headers: Record<string, string>;
  /** The underlying generated @hey-api client, scoped to this call only. */
  client: Client;
}

/**
 * Configure the GeoLens SDK client.
 *
 * @example
 * ```ts
 * import { createGeolensClient } from '@geolens/sdk';
 * import { searchDatasetsEndpointSearchDatasetsGet } from '@geolens/sdk';
 *
 * const sdk = createGeolensClient({
 *   baseUrl: 'https://geolens.example.com/api',
 *   bearerToken: '...',
 * });
 * const resp = await searchDatasetsEndpointSearchDatasetsGet({ client: sdk.client });
 * ```
 */
export const createGeolensClient = (
  opts: GeolensClientOptions,
): GeolensClient => {
  if (opts.bearerToken && opts.apiKey) {
    throw new Error(
      'Provide either bearerToken or apiKey, not both.',
    );
  }

  const headers: Record<string, string> = {};

  if (opts.bearerToken) {
    headers['Authorization'] = `Bearer ${opts.bearerToken}`;
  }
  if (opts.apiKey) {
    headers['X-API-Key'] = opts.apiKey;
  }

  // fix(#1778): build a client scoped to this call instead of mutating the
  // generated module's shared singleton. Two concurrent
  // createGeolensClient() calls (e.g. one per request in a Node server)
  // used to reconfigure the same underlying client object, so the
  // credentials of whichever call ran last leaked onto every other call's
  // in-flight and subsequent requests.
  const scopedClient = createClient(createConfig({
    baseUrl: opts.baseUrl,
    headers,
  }));

  return {
    baseUrl: opts.baseUrl,
    headers,
    client: scopedClient,
  };
};
