// SPDX-License-Identifier: Apache-2.0
/**
 * Auth wrapper for the GeoLens TypeScript SDK.
 *
 * Hand-maintained — NOT regenerated by `make sdks`. The drift gate
 * explicitly excludes this file via `:!sdks/typescript/src/auth.ts` in
 * the Makefile.
 *
 * Backend auth precedence (matches `_resolve_api_key()` in
 * backend/app/modules/auth/dependencies.py):
 *     header X-API-Key  >  JWT Bearer (Authorization)  >  anonymous
 *
 * The query-parameter `?api_key=<key>` fallback that the backend supports
 * for browser/embed contexts is NOT exposed by this SDK wrapper (D-11).
 *
 * Two ways to use the client this returns, both supported:
 *
 * - Pass `{ client: sdk.client }` explicitly to every generated endpoint
 *   call. This client is scoped to THIS `createGeolensClient()` call —
 *   concurrent callers (e.g. one client per request in a Node server)
 *   never interfere with each other (fix(#1778)).
 * - Omit `client` and rely on the legacy shared default: every generated
 *   function falls back to one module-level singleton
 *   (`(options?.client ?? client)`, sdk.gen.ts) that `createGeolensClient()`
 *   also reconfigures on every call, last-caller-wins, exactly as before
 *   this file added the scoped client above. This keeps existing
 *   integrations that never pass `client` working unchanged.
 */
import { client } from './client/client.gen.js';
import { createClient, createConfig, type Client } from './client/client/index.js';

export interface GeolensClientOptions {
  /**
   * Base URL of the GeoLens instance, including the `/api` prefix the
   * deployed API is served under, e.g. https://geolens.example.com/api
   */
  baseUrl: string;
  /** JWT bearer token. Sent as `Authorization: Bearer <token>`. */
  bearerToken?: string;
  /** API key. Sent as `X-API-Key: <key>` (no prefix). */
  apiKey?: string;
}

export interface GeolensClient {
  /** The configured base URL. */
  baseUrl: string;
  /** The headers used for every request. */
  headers: Record<string, string>;
  /**
   * The underlying generated @hey-api client, scoped to this call only.
   * Pass this explicitly (`{ client: sdk.client }`) to isolate this
   * caller from any other concurrent `createGeolensClient()` call. If
   * omitted from a generated call, that call falls back to the shared
   * singleton instead, which this same `createGeolensClient()` call also
   * configures — see the module docblock.
   */
  client: Client;
}

/**
 * Configure the GeoLens SDK client.
 *
 * @example
 * ```ts
 * import { createGeolensClient } from '@geolens/sdk';
 * import { searchDatasetsEndpointSearchDatasetsGet } from '@geolens/sdk';
 *
 * const sdk = createGeolensClient({
 *   baseUrl: 'https://geolens.example.com/api',
 *   bearerToken: '...',
 * });
 * // Isolated: safe alongside a concurrent createGeolensClient() call.
 * const resp = await searchDatasetsEndpointSearchDatasetsGet({ client: sdk.client });
 * // Legacy shared default: works too, but last caller wins process-wide.
 * const resp2 = await searchDatasetsEndpointSearchDatasetsGet();
 * ```
 */
export const createGeolensClient = (
  opts: GeolensClientOptions,
): GeolensClient => {
  if (opts.bearerToken && opts.apiKey) {
    throw new Error(
      'Provide either bearerToken or apiKey, not both.',
    );
  }

  const headers: Record<string, string> = {};

  if (opts.bearerToken) {
    headers['Authorization'] = `Bearer ${opts.bearerToken}`;
  }
  if (opts.apiKey) {
    headers['X-API-Key'] = opts.apiKey;
  }

  // fix(#1778): build a client scoped to this call instead of ONLY
  // mutating the generated module's shared singleton. Two concurrent
  // createGeolensClient() calls (e.g. one per request in a Node server)
  // used to reconfigure the same underlying client object, so the
  // credentials of whichever call ran last leaked onto every other
  // call's in-flight and subsequent requests when that call passed
  // `{ client: sdk.client }` explicitly.
  const scopedClient = createClient(createConfig({
    baseUrl: opts.baseUrl,
    headers,
  }));

  // fix(#1778 review round 3): ALSO reconfigure the shared singleton,
  // exactly as this wrapper did before the scoped client above was
  // added. Existing consumers that call createGeolensClient() once and
  // then call generated endpoints WITHOUT passing `client` rely on the
  // singleton fallback (`options?.client ?? client`, sdk.gen.ts) — those
  // calls broke when the singleton stopped being touched, hitting
  // whatever baseUrl (or none) it last had. This package follows the
  // app's version and this is not a major release, so both call shapes
  // must keep working: `{ client: sdk.client }` is isolated (the bug
  // this PR fixes); omitting `client` keeps the legacy shared default,
  // last-caller-wins, same as always.
  //
  // BUG-023: explicitly clear headers that are NOT provided so a prior
  // call's credentials do not persist on the shared singleton. The
  // @hey-api/client-fetch mergeHeaders implementation deletes a header
  // when its value is null — passing null removes a previously-set one.
  client.setConfig({
    baseUrl: opts.baseUrl,
    headers: {
      Authorization: headers['Authorization'] ?? null,
      'X-API-Key': headers['X-API-Key'] ?? null,
    },
  });

  return {
    baseUrl: opts.baseUrl,
    headers,
    client: scopedClient,
  };
};
