// SPDX-License-Identifier: Apache-2.0
/**
 * File-read response handling for the GeoLens TypeScript SDK.
 *
 * Hand-maintained — NOT regenerated by `make sdks`. Wired into every client
 * `createGeolensClient()` produces (see auth.ts); cannot live in generated
 * code, which @hey-api/openapi-ts owns outright.
 *
 * The generated fetch client (client/client/client.gen.ts) infers its
 * parsed response type from Content-Type (`getParseAs` in
 * client/client/utils.gen.ts), and only a handful of prefixes become a
 * Blob. These routes' declared bodies are `Blob | File`, but a type outside
 * that list — `model/gltf-binary`, `application/json` for tileset.json,
 * `text/csv` for a CSV export — parses as JSON or text instead, never
 * matching the Blob case. Fixed below, scoped by request path to the
 * routes that declare a binary body: COG download, dataset export, a 3D
 * Tiles file and a COPC point cloud file.
 *
 * A 304 from a conditional read (`If-None-Match` or `If-Modified-Since`) on
 * these same routes is a successful revalidation with no body, but the
 * client treats any non-2xx status as an error — see `notModified` below,
 * which reads that signal from the call's own result rather than rewriting
 * the response.
 */
import type { Client } from './client/client/index.js';

// Matched against the request URL's pathname, so a deployment's base path
// prefix (e.g. `/api`) never affects the match.
const FILE_READ_PATHS = [
  /\/datasets\/[^/]+\/download\/cog$/,
  /\/datasets\/[^/]+\/export$/,
  /\/datasets\/[^/]+\/tiles3d\/.+$/,
  /\/datasets\/[^/]+\/copc\/[^/]+\/[^/]+\.copc\.laz$/,
];

function isFileReadPath(pathname: string): boolean {
  return FILE_READ_PATHS.some((pattern) => pattern.test(pathname));
}

const installed = new WeakSet<Client>();

/** Idempotent per client — safe to call every time a client is (re)configured. */
export function installFileReadHandling(target: Client): void {
  if (installed.has(target)) {
    return;
  }
  installed.add(target);

  target.interceptors.request.use((request, options) => {
    const opts = options as { parseAs?: string };
    // Only when the caller hasn't chosen a parser: an explicit `parseAs`
    // (e.g. 'stream', to avoid buffering a large COG or export in memory)
    // must still win over this route-level default.
    if (
      isFileReadPath(new URL(request.url).pathname) &&
      (opts.parseAs === undefined || opts.parseAs === 'auto')
    ) {
      // The same options object the client reads `parseAs` from after this
      // interceptor returns (client.gen.ts's `request()`).
      opts.parseAs = 'blob';
    }
    return request;
  });
}

/**
 * True when `result` (a generated call's non-throwing return value) is a
 * conditional read's cache hit: a 304 answering a request that sent
 * `If-None-Match` or `If-Modified-Since`. With `throwOnError` a 304 throws
 * before a result exists — call these file-read routes without it to use this.
 */
export function notModified(result: { request?: Request; response?: Response }): boolean {
  const sent = result.request?.headers;
  return (
    result.response?.status === 304 &&
    sent !== undefined &&
    (sent.has('if-none-match') || sent.has('if-modified-since'))
  );
}
