// SPDX-License-Identifier: Apache-2.0
/**
 * Redirect handling for the GeoLens TypeScript SDK.
 *
 * Hand-maintained — NOT regenerated by `make sdks`. Wired into every client
 * `createGeolensClient()` produces (see auth.ts) and into the generated
 * singleton (see index.ts).
 *
 * A request that leaves the GeoLens origin through a redirect carries no
 * cookies and none of the original request's headers except `Range` and the
 * `If-*` preconditions, and goes through the global `fetch`, never the
 * client's `fetch` option. (On Node, a proxy set with undici's
 * `setGlobalDispatcher` still applies.) Every request goes out with
 * `redirect: 'manual'`, and a redirect answering a GET or HEAD is then
 * handled here:
 *
 * - Where the redirect response is readable (Node), the SDK follows it: at
 *   most 20 hops, to http(s) URLs only. A hop that stays on the GeoLens
 *   origin resends the request unchanged. From the first hop to another
 *   origin on, requests carry only the headers named above.
 * - A browser hides the redirect's target (an `opaqueredirect` response). A
 *   request with `Authorization` or `X-API-Key` throws {@link RedirectError}.
 *   Any other is sent once more with only the headers named above and
 *   `credentials: 'omit'`, and the browser follows it. For a COG download
 *   from a browser, mint a download token
 *   (`POST /auth/download-token/{dataset_id}`) and fetch
 *   `/datasets/{dataset_id}/download/cog?token=...` without credentials.
 *
 * A redirect answering any other method is returned unfollowed. Streaming
 * (SSE) calls don't read the `fetch` option, so their manual mode comes from
 * the request alone, which a later request interceptor can replace.
 *
 * Every hop, and the browser's resend, keeps the request's `mode`, `cache`,
 * `referrerPolicy`, `integrity` and abort signal. A `mode: 'same-origin'`
 * request redirected to another origin rejects with a TypeError, as fetch
 * does.
 *
 * All of the above applies to the default `redirect: 'follow'`. A caller
 * that sets `redirect` per call or on the client gets what fetch gives:
 * `'manual'` returns the redirect unfollowed, and `'error'` rejects it with
 * a TypeError.
 */
import type { Client } from './client/client/index.js';

const MAX_REDIRECTS = 20;
const REDIRECT_STATUSES = new Set([301, 302, 303, 307, 308]);
const CREDENTIAL_HEADERS = ['authorization', 'x-api-key'];
// Not credentials, and a ranged or conditional read needs them at the
// storage host the backend redirects to.
const FORWARDED_HEADERS = [
  'range',
  'if-range',
  'if-match',
  'if-none-match',
  'if-modified-since',
  'if-unmodified-since',
];

/** A redirect the SDK would not follow. */
export class RedirectError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'RedirectError';
  }
}

const installed = new WeakSet<Client>();

/** Idempotent per client — safe to call every time a client is (re)configured. */
export function installRedirectHandling(target: Client): void {
  if (installed.has(target)) {
    return;
  }
  installed.add(target);

  target.interceptors.request.use((request, options) => {
    // The client reads `fetch` after every request interceptor has run, so a
    // later interceptor that rebuilds the request can't turn following back on.
    const clientFetch = options.fetch ?? globalThis.fetch;
    options.fetch = (input, init) => clientFetch(new Request(input, { ...init, redirect: 'manual' }));
    return new Request(request, { redirect: 'manual' });
  });
  target.interceptors.response.use((response, request, options) => {
    const policy = options.redirect ?? 'follow';
    if (policy === 'manual') {
      return response;
    }
    if (policy === 'error') {
      if (response.type === 'opaqueredirect' || REDIRECT_STATUSES.has(response.status)) {
        throw new TypeError('unexpected redirect');
      }
      return response;
    }
    return followRedirect(response, request, options.fetch!);
  });
}

async function followRedirect(
  response: Response,
  request: Request,
  clientFetch: typeof fetch,
): Promise<Response> {
  if (request.method !== 'GET' && request.method !== 'HEAD') {
    return response;
  }
  if (response.type === 'opaqueredirect') {
    if (CREDENTIAL_HEADERS.some((name) => request.headers.has(name))) {
      throw new RedirectError(
        'The server redirected a request that carries credentials, and a browser ' +
          'hides where to. Use a download token for file downloads instead.',
      );
    }
    return globalThis.fetch(
      new Request(request.url, {
        ...carried(request),
        method: request.method,
        headers: forwarded(request.headers),
        redirect: 'follow',
        credentials: 'omit',
      }),
    );
  }

  const origin = new URL(request.url).origin;
  let current = request;
  let leftOrigin = false;
  for (let hops = 0; isRedirect(response); hops++) {
    if (hops === MAX_REDIRECTS) {
      throw new RedirectError(`Stopped after ${MAX_REDIRECTS} redirects`);
    }
    const target = new URL(response.headers.get('location')!, current.url);
    // The URL stays out of the message: a presigned URL is a credential.
    if (target.protocol !== 'http:' && target.protocol !== 'https:') {
      throw new RedirectError(`Redirected to an unsupported URL scheme: ${target.protocol}`);
    }
    if (request.mode === 'same-origin' && target.origin !== origin) {
      throw new TypeError('A same-origin request was redirected to another origin');
    }
    await response.body?.cancel();
    leftOrigin ||= target.origin !== origin;
    current = new Request(target, {
      ...carried(request),
      method: request.method,
      headers: leftOrigin ? forwarded(current.headers) : current.headers,
      redirect: 'manual',
    });
    response = await (leftOrigin ? globalThis.fetch(current) : clientFetch(current));
  }
  return response;
}

function carried(request: Request): RequestInit {
  return {
    mode: request.mode,
    cache: request.cache,
    referrerPolicy: request.referrerPolicy,
    integrity: request.integrity,
    signal: request.signal,
  };
}

function forwarded(headers: Headers): Headers {
  const kept = new Headers();
  for (const name of FORWARDED_HEADERS) {
    const value = headers.get(name);
    if (value !== null) {
      kept.set(name, value);
    }
  }
  return kept;
}

function isRedirect(response: Response): boolean {
  return REDIRECT_STATUSES.has(response.status) && response.headers.has('location');
}
