/**
 * contour-sync.ts
 *
 * Companion-layer sync for DEM contour overlays (EDITOR-DEM-04).
 *
 * Reads builder-private `_contour-*` paint keys from an AdapterLayerInput and
 * adds / removes / updates a companion MapLibre `line` layer that renders
 * client-side contour vector tiles generated by `maplibre-contour`.
 *
 * Key design rules:
 *  - DemSource is registered exactly ONCE per raster-dem sourceId (Pitfall 4 /
 *    anti-pattern: do NOT share DemSource across multiple layers without keying
 *    by sourceId — see 1140-RESEARCH.md).
 *  - `_contour-*` keys are builder-private and MUST NOT be added to
 *    RASTER_OWNED_PAINT_PROPERTIES (Pitfall 6).
 *  - The contour source is added to `desiredSources` only while enabled, so
 *    `removeStaleSourcesAndLayers` in map-sync.ts keeps it alive when enabled
 *    and drops it when the toggle is off.
 *  - The whole function body is wrapped in a try/catch so a missing source or
 *    pre-idle map degrades gracefully (never throws inside the sync loop).
 */

import type { Map as MaplibreMap } from 'maplibre-gl';
import mlcontour from 'maplibre-contour';
import type { AdapterLayerInput } from './layer-adapters/types';

// The DemSource class is a value in the default export; derive its instance type here.
type DemSource = InstanceType<typeof mlcontour.DemSource>;

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/**
 * Resolve a relative tile URL to an absolute one.
 * Duplicated from map-sync.ts (not exported there) to avoid a circular dep.
 */
function absolutizeTileUrl(tileUrl: string): string {
  if (tileUrl.startsWith('http')) return tileUrl;
  const origin = typeof window === 'undefined' ? '' : window.location.origin;
  return `${origin}${tileUrl}`;
}

/**
 * Map a single user-facing interval (metres) to a per-zoom threshold dict.
 * Standard cartographic practice: show only coarse lines at low zoom, add
 * detail as the user zooms in.
 *
 *   z ≤ 9  → [interval * 5]            (one coarse contour line)
 *   z 10-12 → [interval, interval * 5] (major + coarse)
 *   z ≥ 13 → [Math.max(10, interval / 2), interval]  (minor + major)
 *
 * The minimum threshold is clamped to 10 m (the slider min) to avoid
 * generating infinitely-dense contours at high zoom.
 */
function intervalToThresholds(interval: number): { [zoom: number]: number[] } {
  const safeInterval = Math.max(10, interval);
  const minor = Math.max(10, Math.floor(safeInterval / 2));
  return {
    9: [safeInterval * 5],
    11: [safeInterval, safeInterval * 5],
    13: [minor, safeInterval],
  };
}

// ---------------------------------------------------------------------------
// Module-level DemSource registry (keyed by raster-dem sourceId)
// ---------------------------------------------------------------------------

/**
 * Module-level registry of DemSource instances.
 * Exported for testing; do NOT mutate externally.
 */
export const _demSources = new Map<string, DemSource>();

/**
 * Lazily construct and register a DemSource for `sourceId`.
 * `setupMaplibre` is called exactly once per sourceId.
 *
 * The `map` argument must be a maplibre Map that accepts `addProtocol` — in
 * practice this means the style has finished loading (called from within the
 * sync loop, which runs after idle).
 */
export function ensureDemSource(
  map: MaplibreMap,
  sourceId: string,
  tileUrl: string,
): DemSource {
  if (_demSources.has(sourceId)) {
    return _demSources.get(sourceId)!;
  }
  const demSource = new mlcontour.DemSource({
    url: absolutizeTileUrl(tileUrl),
    encoding: 'mapbox',
    maxzoom: 18,
    worker: true,
  });
  // setupMaplibre registers the custom protocol handlers on the maplibre global.
  // It must run AFTER the map is ready (Pitfall 4).
  demSource.setupMaplibre(map as unknown as Parameters<typeof demSource.setupMaplibre>[0]);
  _demSources.set(sourceId, demSource);
  return demSource;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Sync the companion contour `line` layer for a DEM raster layer.
 *
 * Must be called AFTER `syncRasterLayer` so the raster-dem source already
 * exists on the map.
 *
 * @param map            - The live MapLibre map instance.
 * @param input          - The AdapterLayerInput built in syncLayersToMap.
 * @param desiredSources - The set that tracks which sources should survive
 *                         `removeStaleSourcesAndLayers`. Add the contour
 *                         source id here when enabled so it is not pruned.
 */
export function syncContourLayer(
  map: MaplibreMap,
  input: AdapterLayerInput,
  desiredSources: Set<string>,
): void {
  try {
    const contourLayerId = `${input.layerId}-contour`;
    const contourSourceId = `${input.sourceId}-contour`;
    const enabled = input.paint['_contour-enabled'] === true;

    if (!enabled) {
      // Remove the companion line layer if present.
      if (map.getLayer(contourLayerId)) {
        map.removeLayer(contourLayerId);
      }
      // Remove the vector source if present. Do NOT add to desiredSources —
      // removeStaleSourcesAndLayers will prune it on the next sync cycle.
      if (map.getSource(contourSourceId)) {
        map.removeSource(contourSourceId);
      }
      // Release the DemSource (and its Web Worker) from the module-level registry
      // so it is not returned stale if the same sourceId is re-added later (e.g.
      // after auth token rotation or re-adding the same dataset).
      _demSources.delete(input.sourceId);
      return;
    }

    // Read builder-private paint values with safe fallbacks.
    const interval = typeof input.paint['_contour-interval'] === 'number'
      ? (input.paint['_contour-interval'] as number)
      : 100;
    const color = typeof input.paint['_contour-color'] === 'string'
      ? (input.paint['_contour-color'] as string)
      : '#555555';
    const weight = typeof input.paint['_contour-weight'] === 'number'
      ? (input.paint['_contour-weight'] as number)
      : 1;

    // Ensure the DemSource is registered on the map (once per sourceId).
    const demSource = ensureDemSource(map, input.sourceId, input.tileUrl);

    const thresholds = intervalToThresholds(interval);
    const contourProtocolUrl = demSource.contourProtocolUrl({
      thresholds,
      contourLayer: 'contours',
      elevationKey: 'ele',
      levelKey: 'level',
      overzoom: 1,
    });

    // Add the vector source if not already present; otherwise update its tile URL
    // so that interval/threshold changes take effect on the existing source.
    // VectorTileSource.setTiles() is available in MapLibre GL JS 5.x.
    const existingContourSource = map.getSource(contourSourceId) as
      | { setTiles?: (tiles: string[]) => void; serialize?: () => { tiles?: string[] } }
      | undefined;
    if (!existingContourSource) {
      map.addSource(contourSourceId, {
        type: 'vector',
        tiles: [contourProtocolUrl],
      });
    } else {
      // Only call setTiles when the URL actually changed to avoid unnecessary tile re-fetches.
      const currentTiles = existingContourSource.serialize?.()?.tiles ?? [];
      if (currentTiles[0] !== contourProtocolUrl) {
        existingContourSource.setTiles?.([contourProtocolUrl]);
      }
    }

    // Track the source so removeStaleSourcesAndLayers does not remove it.
    desiredSources.add(contourSourceId);

    if (!map.getLayer(contourLayerId)) {
      // Insert the contour line layer BELOW the hillshade layer so hillshade
      // shading renders on top of the contour lines (before-id = hillshade layer).
      map.addLayer(
        {
          id: contourLayerId,
          type: 'line',
          source: contourSourceId,
          'source-layer': 'contours',
          paint: {
            'line-color': color,
            'line-width': weight,
          },
        },
        input.layerId,
      );
    } else {
      // Layer already exists — update paint properties only.
      map.setPaintProperty(contourLayerId, 'line-color', color);
      map.setPaintProperty(contourLayerId, 'line-width', weight);
    }
  } catch (err) {
    // Degrade gracefully — never throw inside the sync loop.
    if (import.meta.env.DEV) {
      console.warn('[contour-sync] syncContourLayer failed', input.layerId, err);
    }
  }
}
