// Security regression tests — auto-generated by /sec-audit (2026-05-19)
//
// Run: npx playwright test e2e/sec-audit.spec.ts --project=chromium
//
// fix(#1778): S01/S02/S03/S05/S08/S09 used to read hand-provisioned env vars
// (SEC_AUDIT_PRIVATE_DATASET_ID etc.) that nothing in CI ever set, so those
// tests skipped on every run and the file reported green while covering 8
// of 19 cases. beforeAll below seeds the same fixtures in-spec instead, the
// way e2e/auth.setup.ts seeds a shared dataset and e2e/auth.spec.ts creates
// its throwaway e2e-logout-probe user.
//
// S04 (SSRF redirect bypass) is the one case left out: it needs a live
// external URL that 302-redirects to 169.254.169.254, which cannot be
// provisioned safely in CI. That behavior is covered by
// backend/tests/test_ssrf_redirect.py, so the test is removed below rather
// than left permanently skipped — see the comment where it used to be.
//
//   SEC_AUDIT_FRONTEND_URL    override the frontend base for S08 (default E2E_BASE_URL)

import { test, expect } from '@playwright/test';
import { getAuthToken, seedDataset, seedDemDataset, deleteDataset } from './helpers/catalog';

const BASE_URL = process.env.E2E_BASE_URL ?? 'http://localhost:8080';
// fix(review #1792): SEC_AUDIT_API_URL used to let audit requests target a
// different host than the one fixtures were seeded on -- nothing in CI or
// any playwright*.config.ts ever set it, but if it had been, every
// IDOR/visibility assertion below would have passed vacuously (a foreign id
// 404s against the wrong host regardless of authorization). Removed the
// override; one apiBase feeds seeding, publishing, and auditing alike, so
// they cannot drift apart.
const apiBase = `${BASE_URL}/api`;

let privateDatasetId = '';
let privateDatasetTitle = '';
let privateRasterId = '';
let privateRasterTitle = '';
let publicDatasetId = '';
let publicDatasetTitle = '';
let editorBToken = '';
let editorBUserId = '';
let shareToken = '';
let shareMapId = '';

function adminHeaders(): Record<string, string> {
  return {
    Authorization: `Bearer ${getAuthToken()}`,
    'Content-Type': 'application/json',
  };
}

test.beforeAll(async () => {
  const headers = adminHeaders();

  // S01: private, published raster. The STAC /stac/items/{id} endpoint uses
  // Dataset.id as the item id (backend/tests/test_stac_visibility.py), and
  // ingest defaults a new dataset to visibility=private, record_status=published.
  const raster = await seedDemDataset();
  privateRasterId = raster.id;
  privateRasterTitle = raster.title;

  // S02/S03/S05: private vector dataset owned by the seeding admin account.
  const priv = await seedDataset('Sec Audit Private');
  privateDatasetId = priv.id;
  privateDatasetTitle = priv.title;

  // S09: public, published vector dataset.
  const pub = await seedDataset('Sec Audit Public');
  publicDatasetId = pub.id;
  publicDatasetTitle = pub.title;
  const publishRes = await fetch(`${apiBase}/datasets/${publicDatasetId}`, {
    method: 'PATCH',
    headers,
    body: JSON.stringify({ visibility: 'public', record_status: 'published' }),
  });
  if (!publishRes.ok) {
    throw new Error(`sec-audit: could not publish public dataset: ${publishRes.status}`);
  }

  // S02/S03: a second, non-admin editor who owns neither dataset above.
  const editorBUsername = `sec-audit-editor-b-${Date.now()}`;
  const editorBPassword = 'Sec-Audit-Editor-B-42';
  const createUserRes = await fetch(`${apiBase}/admin/users/`, {
    method: 'POST',
    headers,
    body: JSON.stringify({ username: editorBUsername, password: editorBPassword, role: 'editor' }),
  });
  if (!createUserRes.ok) {
    throw new Error(`sec-audit: could not create editor B: ${createUserRes.status}`);
  }
  editorBUserId = ((await createUserRes.json()) as { id: string }).id;

  const loginRes = await fetch(`${apiBase}/auth/login/`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: new URLSearchParams({ username: editorBUsername, password: editorBPassword }).toString(),
  });
  if (!loginRes.ok) {
    throw new Error(`sec-audit: could not log in editor B: ${loginRes.status}`);
  }
  editorBToken = ((await loginRes.json()) as { access_token: string }).access_token;

  // S08: a public map with a share token.
  const mapRes = await fetch(`${apiBase}/maps/`, {
    method: 'POST',
    headers,
    body: JSON.stringify({ name: `Sec Audit Share Map ${Date.now()}` }),
  });
  if (!mapRes.ok) {
    throw new Error(`sec-audit: could not create share map: ${mapRes.status}`);
  }
  shareMapId = ((await mapRes.json()) as { id: string }).id;
  const mapPublishRes = await fetch(`${apiBase}/maps/${shareMapId}`, {
    method: 'PUT',
    headers,
    body: JSON.stringify({ visibility: 'public' }),
  });
  if (!mapPublishRes.ok) {
    throw new Error(`sec-audit: could not publish share map: ${mapPublishRes.status}`);
  }
  const shareRes = await fetch(`${apiBase}/maps/${shareMapId}/share/`, {
    method: 'POST',
    headers,
  });
  if (!shareRes.ok) {
    throw new Error(`sec-audit: could not create share token: ${shareRes.status}`);
  }
  shareToken = ((await shareRes.json()) as { token: string }).token;
});

test.afterAll(async () => {
  const headers = adminHeaders();
  if (shareMapId) {
    await fetch(`${apiBase}/maps/${shareMapId}`, { method: 'DELETE', headers }).catch(() => {});
  }
  if (editorBUserId) {
    await fetch(`${apiBase}/admin/users/${editorBUserId}`, { method: 'DELETE', headers }).catch(() => {});
  }
  if (privateDatasetId) await deleteDataset(privateDatasetId, privateDatasetTitle);
  if (publicDatasetId) await deleteDataset(publicDatasetId, publicDatasetTitle);
  if (privateRasterId) await deleteDataset(privateRasterId, privateRasterTitle);
});

// ─────────────────────────────────────────────────────────────────────────────
// S01 — STAC visibility bypass (anonymous read of private raster)
// ─────────────────────────────────────────────────────────────────────────────

test('S01 STAC visibility — anonymous cannot read a private raster STAC item', async ({ request }) => {
  const recordId = privateRasterId;
  const res = await request.get(`${apiBase}/stac/items/${recordId}`);
  expect([401, 403, 404]).toContain(res.status());
});

test('S01 STAC visibility — anonymous /stac/search does not return private rasters', async ({ request }) => {
  const recordId = privateRasterId;
  const res = await request.get(`${apiBase}/stac/search?ids=${recordId}`);
  // Either denied (401/403) or empty features list — never the private item back
  if (res.status() === 200) {
    const body = await res.json();
    const features = body.features ?? [];
    const hit = features.find((f: { id: string }) => f.id === recordId);
    expect(hit).toBeUndefined();
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// S02 — Dataset metadata IDOR — editor B mutates user A's private dataset
// ─────────────────────────────────────────────────────────────────────────────

test('S02 IDOR — editor B cannot PATCH another user\'s private dataset', async ({ request }) => {
  const datasetId = privateDatasetId;
  const tokenB = editorBToken;
  // fix(review #1792): the real route is /datasets/{dataset_id} with NO
  // trailing slash (backend/openapi.json has a single, slash-less entry;
  // redirect_slashes=False means a trailing-slash request 404s before the
  // handler runs). The old URL's 404 happened to fall inside this test's
  // accepted [401, 403, 404] range, so it passed without ever exercising
  // check_dataset_write_access.
  const res = await request.patch(`${apiBase}/datasets/${datasetId}`, {
    headers: {
      Authorization: `Bearer ${tokenB}`,
      'Content-Type': 'application/json',
    },
    data: { title: 'sec-audit-S02-attempt' },
  });
  expect([401, 403, 404]).toContain(res.status());
});

test('S02 IDOR — editor B cannot DELETE another user\'s private dataset', async ({ request }) => {
  const datasetId = privateDatasetId;
  const tokenB = editorBToken;
  // fix(review #1792): delete_dataset_endpoint requires a DatasetDeleteRequest
  // body with confirm_title (router.py:530-549) -- an empty DELETE 422s
  // before the ownership check ever runs, so this failed on a correct
  // server regardless of authorization. Send the real title so the only
  // thing that can still refuse the request is authorization. Also dropped
  // the trailing slash: the real route is /datasets/{dataset_id} with NONE
  // (backend/openapi.json has a single, slash-less entry; redirect_slashes
  // =False means a trailing-slash request 404s before the handler runs) --
  // the old URL's 404 fell inside this test's accepted range too, so it
  // passed without ever exercising check_dataset_write_access. Building the
  // positive control below (same body, real owner) surfaced this: it kept
  // 404ing even for the owner until the slash was dropped.
  const res = await request.delete(`${apiBase}/datasets/${datasetId}`, {
    headers: { Authorization: `Bearer ${tokenB}`, 'Content-Type': 'application/json' },
    data: { confirm_title: privateDatasetTitle },
  });
  expect([401, 403, 404]).toContain(res.status());

  // Positive control: the identical request shape, from the actual owner,
  // succeeds -- proves the 401/403/404 above comes from authorization, not
  // from the server rejecting the body itself for everyone. Uses its own
  // throwaway dataset (not privateDatasetId, which S03 and S05 below still
  // need) so this test owns its own create/delete lifecycle rather than
  // reaching into the shared beforeAll fixtures.
  const throwaway = await seedDataset('Sec Audit S02 Positive Control');
  try {
    const ownerRes = await request.delete(`${apiBase}/datasets/${throwaway.id}`, {
      headers: { Authorization: `Bearer ${getAuthToken()}`, 'Content-Type': 'application/json' },
      data: { confirm_title: throwaway.title },
    });
    expect(ownerRes.status()).toBe(204);
  } finally {
    await deleteDataset(throwaway.id, throwaway.title);
  }
});

test('S02 IDOR — editor B cannot bulk-delete another user\'s private dataset', async ({ request }) => {
  const datasetId = privateDatasetId;
  const tokenB = editorBToken;
  // fix(#1778): BulkDeleteRequest's schema is `{ datasets: [{ dataset_id,
  // confirm_title }] }` (backend/openapi.json), not `{ dataset_ids: [...] }`
  // — the old payload always 422'd before authorization was ever reached,
  // which the permanent skip guard hid. bulk_delete_datasets_endpoint
  // (router.py) isolates per-item failures rather than rejecting the whole
  // batch, so a denied item surfaces as HTTP 200 with a per-item
  // status: 'error', never a top-level 401/403/404.
  const res = await request.post(`${apiBase}/datasets/bulk-delete/`, {
    headers: {
      Authorization: `Bearer ${tokenB}`,
      'Content-Type': 'application/json',
    },
    data: { datasets: [{ dataset_id: datasetId, confirm_title: privateDatasetTitle }] },
  });
  expect(res.status()).toBe(200);
  const body = await res.json();
  // fix(review #1792): `item?.status` on an ABSENT result item is
  // `undefined`, and `expect(undefined).not.toBe('deleted')` passes
  // trivially -- a response that dropped the target dataset from `results`
  // entirely (or never included it) satisfied this assertion just as well
  // as a genuine denial. Assert the item exists, then assert its actual
  // status and the top-level count, both of which BulkDeleteResponse always
  // returns (backend/openapi.json).
  const results: Array<{ dataset_id: string; status: string }> = body.results ?? [];
  const item = results.find((r) => r.dataset_id === datasetId);
  expect(item, 'bulk-delete response should include a result for the target dataset').toBeTruthy();
  expect(item?.status).toBe('error');
  expect(body.deleted).toBe(0);
});

// ─────────────────────────────────────────────────────────────────────────────
// S03 — Column DDL IDOR — editor B drops column on user A's private dataset
// ─────────────────────────────────────────────────────────────────────────────

test('S03 IDOR — editor B cannot add a column to another user\'s private dataset', async ({ request }) => {
  const datasetId = privateDatasetId;
  const tokenB = editorBToken;
  // fix(review #1792): column DDL lives under /layers/{dataset_id}/columns/,
  // not /datasets/{dataset_id}/columns/ (backend/openapi.json has no such
  // /datasets path at all -- add_column_endpoint and drop_column_endpoint
  // are both registered on layers_router). The old URL 404'd unconditionally,
  // which fell inside this test's accepted range, so it passed without ever
  // reaching add_column_endpoint's check_dataset_write_access. The body
  // shape was also wrong: AddColumnRequest wraps the definition in a
  // `column` object (`{ column: { name, type } }`), not top-level
  // `{ name, type }`. Fixing both surfaced a THIRD latent bug: the column
  // name 'sec_audit_S03' has always failed ColumnDef's own name validator
  // (lowercase letters/digits/underscores only) with a 422 -- "body.column.
  // name: Value error, Column name 'sec_audit_S03' must start with a
  // lowercase letter and contain only lowercase letters, digits, and
  // underscores" -- which Pydantic raises before the handler body (and so
  // before check_dataset_write_access) ever runs. Lowercased it.
  const res = await request.post(`${apiBase}/layers/${datasetId}/columns/`, {
    headers: {
      Authorization: `Bearer ${tokenB}`,
      'Content-Type': 'application/json',
    },
    data: { column: { name: 'sec_audit_s03', type: 'text' } },
  });
  expect([401, 403, 404]).toContain(res.status());
});

test('S03 IDOR — editor B cannot DROP a column on another user\'s private dataset', async ({ request }) => {
  const datasetId = privateDatasetId;
  const tokenB = editorBToken;
  // fix(review #1792): same /layers/{dataset_id}/columns/{column_name} path
  // fix as the add-column test above (drop_column_endpoint is on
  // layers_router too; no trailing slash on this one per openapi.json).
  // Use a column name that almost certainly exists on a default ingested table
  const res = await request.delete(`${apiBase}/layers/${datasetId}/columns/gid`, {
    headers: { Authorization: `Bearer ${tokenB}` },
  });
  expect([401, 403, 404]).toContain(res.status());
});

// ─────────────────────────────────────────────────────────────────────────────
// S04 — SSRF redirect bypass on external source connectors
//
// fix(#1778): removed rather than left permanently skipped. This test needs
// a live external URL that 302-redirects to 169.254.169.254; CI has no such
// endpoint and standing one up is a real infrastructure dependency, not a
// fixture this spec can seed. The redirect-revalidation behavior itself is
// covered by backend/tests/test_ssrf_redirect.py, which mocks the redirect.
// ─────────────────────────────────────────────────────────────────────────────

// ─────────────────────────────────────────────────────────────────────────────
// S05 — pgvector /datasets/{id}/related/ visibility bypass
// ─────────────────────────────────────────────────────────────────────────────

test('S05 VEC-IDOR — anonymous /related/ on a private dataset returns no oracle', async ({ request }) => {
  const datasetId = privateDatasetId;
  const res = await request.get(`${apiBase}/datasets/${datasetId}/related/`);
  // After fix: 401/403/404. Before fix: 200 with empty or partial list (oracle).
  // Empty 200 is also accepted as long as no similarity scores leak.
  if (res.status() === 200) {
    const body = await res.json();
    const items = Array.isArray(body) ? body : (body.items ?? []);
    expect(items.length).toBe(0);
  } else {
    expect([401, 403, 404]).toContain(res.status());
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// S06 — Demo credentials not accepted by default
// ─────────────────────────────────────────────────────────────────────────────

test('S06 — admin user with known-public password "demodemo" cannot log in', async ({ request }) => {
  const res = await request.post(`${apiBase}/auth/login/`, {
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    form: { username: 'admin', password: 'demodemo' },
  });
  expect([400, 401]).toContain(res.status());
});

// ─────────────────────────────────────────────────────────────────────────────
// S08 — Embed-token framing (after fix: per-token frame-ancestors CSP exists)
// ─────────────────────────────────────────────────────────────────────────────

test('S08 — /m/<share_token> HTML response has frame-ancestors CSP (or is admin-restricted)', async ({ request }) => {
  // The frontend host serves /m/* — derive from API base
  const frontendBase = process.env.SEC_AUDIT_FRONTEND_URL || 'http://localhost:8080';
  const res = await request.get(`${frontendBase}/m/${shareToken}?embed=true`, {
    headers: { Accept: 'text/html' },
  });
  if (res.status() === 200) {
    // After S08 fix: either CSP frame-ancestors carries the embed-token's allowed_origins,
    // or the response is admin-only (no public embed). DENY/SAMEORIGIN with no CSP is the pre-fix state.
    const csp = res.headers()['content-security-policy'] || '';
    const xfo = res.headers()['x-frame-options'] || '';
    const hasFrameAncestors = csp.includes('frame-ancestors');
    const isRestrictive = ['DENY', 'SAMEORIGIN'].includes(xfo.toUpperCase());
    // Fail only the pre-fix state: SAMEORIGIN+no CSP frame-ancestors (= product contradiction)
    expect(hasFrameAncestors || !isRestrictive).toBe(true);
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// S09 — ogr2ogr -where parser rejects SQL grammar (UNION, subqueries)
// ─────────────────────────────────────────────────────────────────────────────

test('S09 — dataset export -where rejects UNION / subqueries', async ({ request }) => {
  const datasetId = publicDatasetId;
  const malicious = `gid > 0 UNION SELECT 1, 2, 3`;
  // fix(#1778): the export route is /datasets/{id}/export?format=csv, not
  // /datasets/{id}/export.csv (backend/openapi.json has no such path) — the
  // old URL always 404'd before the -where parser ever ran, which the
  // permanent skip guard hid.
  const res = await request.get(
    `${apiBase}/datasets/${datasetId}/export?format=csv&where=${encodeURIComponent(malicious)}`,
  );
  expect([400, 422, 403]).toContain(res.status());
});

// ─────────────────────────────────────────────────────────────────────────────
// S11 — Per-route rate limiting on semantic search
// ─────────────────────────────────────────────────────────────────────────────

test('S11 — burst of unique semantic queries gets rate-limited', async ({ request }) => {
  // fix(#1778): the skip guard used to fire on exactly the outcome this test
  // exists to catch, so it could never go red. The per-route decorator has
  // shipped (search/router.py's search_datasets_endpoint carries
  // @limiter.limit(_semantic_search_rate_limit)) -- gate on it.
  //
  // fix(review #1792): a hardcoded 80-request burst assumed the 30/minute
  // default, but semantic_search_rate_limit is a runtime admin setting
  // (persistent_config.py) an operator can raise up to 1000. Read the
  // actual configured value through /settings/all/ (admin-only) using the
  // same shared admin session every other fixture in this file uses, and
  // send exactly one more request than that.
  const settingsRes = await request.get(`${apiBase}/settings/all/`, {
    headers: { Authorization: `Bearer ${getAuthToken()}` },
  });
  expect(settingsRes.ok()).toBeTruthy();
  const settingsBody = (await settingsRes.json()) as {
    tabs: Record<string, Array<{ key: string; value: unknown }>>;
  };
  const rateLimitItem = Object.values(settingsBody.tabs)
    .flat()
    .find((item) => item.key === 'semantic_search_rate_limit');
  expect(
    rateLimitItem,
    'semantic_search_rate_limit setting not found in /settings/all/',
  ).toBeTruthy();
  const configuredLimit = Number(rateLimitItem?.value);
  expect(Number.isFinite(configuredLimit) && configuredLimit > 0).toBe(true);

  // The e2e suite shares one admin session across parallel specs, so this
  // deliberately does NOT set/restore the limit -- mutating a global setting
  // here would race whatever else is reading it concurrently. A configured
  // ceiling above 200 would make this test send hundreds of load-generating
  // requests just to find the boundary; fail loudly with the observed value
  // instead of doing that silently.
  const REQUEST_CEILING = 200;
  expect(
    configuredLimit,
    `semantic_search_rate_limit is ${configuredLimit}, above this test's ` +
      `${REQUEST_CEILING}-request ceiling -- raise the ceiling deliberately ` +
      'or lower the configured limit for this environment',
  ).toBeLessThanOrEqual(REQUEST_CEILING);

  const requestCount = configuredLimit + 1;
  const responses = await Promise.all(
    Array.from({ length: requestCount }, (_, i) =>
      request.get(`${apiBase}/search/datasets/?q=sec-audit-S11-unique-token-${i}`)
    ),
  );
  const statuses = responses.map((r) => r.status());
  expect(statuses).toContain(429);
});

// ─────────────────────────────────────────────────────────────────────────────
// S13 — /search/facets/ rejects oversized q
// ─────────────────────────────────────────────────────────────────────────────

test('S13 — /search/facets/ rejects q longer than 1000 chars', async ({ request }) => {
  const longQ = 'a'.repeat(5000);
  const res = await request.get(`${apiBase}/search/facets/?q=${encodeURIComponent(longQ)}`);
  // After fix: 422 (Pydantic validation). Pre-fix: 200 with seq-scan.
  // 429: the S11 burst test above can leave the per-IP rate limiter saturated
  // within the same window — a safe rejection still satisfies this hygiene check.
  expect([400, 422, 429]).toContain(res.status());
});

// ─────────────────────────────────────────────────────────────────────────────
// Hygiene regression — ensure SQL injection sentinels remain blocked
// ─────────────────────────────────────────────────────────────────────────────

test('hygiene — SQLi sentinel in search q does not crash or return all rows', async ({ request }) => {
  const res = await request.get(`${apiBase}/search/datasets/?q=` + encodeURIComponent(`' OR '1'='1`));
  expect([200, 400, 422, 429]).toContain(res.status()); // 429: safe rate-limit rejection (S11 burst bleed)
  if (res.status() === 200) {
    const body = await res.json();
    const features = body.features ?? [];
    // Sentinel should match nothing; ensure response is bounded (LIMIT 200 cap)
    expect(features.length).toBeLessThanOrEqual(200);
  }
});

test('hygiene — pgvector embedding never appears in search response', async ({ request }) => {
  const res = await request.get(`${apiBase}/search/datasets/?q=test`);
  if (res.status() === 200) {
    const body = await res.json();
    const features = body.features ?? [];
    for (const f of features) {
      expect(f.embedding).toBeUndefined();
      expect(f.vector).toBeUndefined();
      expect(f.properties?.embedding).toBeUndefined();
      expect(f.properties?.vector).toBeUndefined();
    }
  }
});

test('hygiene — pg_trgm operator-abuse handled safely (no syntax error, fast response)', async ({ request }) => {
  const malicious = '! | !';
  const start = Date.now();
  const res = await request.get(`${apiBase}/search/datasets/?q=${encodeURIComponent(malicious)}`);
  const elapsed = Date.now() - start;
  expect(elapsed).toBeLessThan(3000);
  expect([200, 400, 422, 429]).toContain(res.status()); // 429: safe rate-limit rejection (S11 burst bleed)
});

test('hygiene — malformed bbox is rejected', async ({ request }) => {
  const res = await request.get(`${apiBase}/search/datasets/?bbox=0,0,1`);
  expect([400, 422, 429]).toContain(res.status()); // 429: safe rate-limit rejection (S11 burst bleed)
});

test('hygiene — CORS does not grant credentials to an untrusted origin', async ({ request }) => {
  const origin = 'http://attacker.example';
  const appResponse = await request.get(`${apiBase}/auth/me/`, {
    headers: { Origin: origin },
  });
  expect(appResponse.headers()['access-control-allow-origin']).toBeUndefined();
  expect(appResponse.headers()['access-control-allow-credentials']).toBeUndefined();

  // Anonymous standards routes may use a wildcard, but never with credentials.
  const standardsResponse = await request.get(`${apiBase}/`, {
    headers: { Origin: 'http://attacker.example' },
  });
  const standardsOrigin = standardsResponse.headers()['access-control-allow-origin'];
  expect(standardsOrigin).not.toBe(origin);
  if (standardsOrigin === '*') {
    expect(
      standardsResponse.headers()['access-control-allow-credentials'],
    ).toBeUndefined();
  }
});
