// Security regression tests — auto-generated by /sec-audit (2026-05-19)
//
// Run: npx playwright test e2e/sec-audit.spec.ts --project=chromium
//
// Many tests need a private dataset / raster / second editor user. Provide via env:
//   SEC_AUDIT_API_URL                  default /api
//   SEC_AUDIT_PRIVATE_RECORD_ID        STAC record_id for a private published raster (S01)
//   SEC_AUDIT_PRIVATE_DATASET_ID       a dataset owned by user A with visibility=private (S02/S03/S05)
//   SEC_AUDIT_EDITOR_B_TOKEN           bearer token for a second editor user (not the dataset's owner) (S02/S03)
//   SEC_AUDIT_EDITOR_A_TOKEN           bearer token for the dataset owner (S03 cleanup)
//   SEC_AUDIT_SSRF_TEST_REDIRECTOR     a public URL that 302-redirects to 169.254.169.254 (S04)
// Tests that lack the env var skip with a printed reason rather than fail.

import { test, expect } from '@playwright/test';

const API = process.env.SEC_AUDIT_API_URL || '/api';

// ─────────────────────────────────────────────────────────────────────────────
// S01 — STAC visibility bypass (anonymous read of private raster)
// ─────────────────────────────────────────────────────────────────────────────

test('S01 STAC visibility — anonymous cannot read a private raster STAC item', async ({ request }) => {
  const recordId = process.env.SEC_AUDIT_PRIVATE_RECORD_ID;
  test.skip(!recordId, 'Set SEC_AUDIT_PRIVATE_RECORD_ID to a private published raster');
  const res = await request.get(`${API}/stac/items/${recordId}`);
  expect([401, 403, 404]).toContain(res.status());
});

test('S01 STAC visibility — anonymous /stac/search does not return private rasters', async ({ request }) => {
  const recordId = process.env.SEC_AUDIT_PRIVATE_RECORD_ID;
  test.skip(!recordId, 'Set SEC_AUDIT_PRIVATE_RECORD_ID to a private published raster');
  const res = await request.get(`${API}/stac/search?ids=${recordId}`);
  // Either denied (401/403) or empty features list — never the private item back
  if (res.status() === 200) {
    const body = await res.json();
    const features = body.features ?? [];
    const hit = features.find((f: { id: string }) => f.id === recordId);
    expect(hit).toBeUndefined();
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// S02 — Dataset metadata IDOR — editor B mutates user A's private dataset
// ─────────────────────────────────────────────────────────────────────────────

test('S02 IDOR — editor B cannot PATCH another user\'s private dataset', async ({ request }) => {
  const datasetId = process.env.SEC_AUDIT_PRIVATE_DATASET_ID;
  const tokenB = process.env.SEC_AUDIT_EDITOR_B_TOKEN;
  test.skip(!datasetId || !tokenB, 'Set SEC_AUDIT_PRIVATE_DATASET_ID and SEC_AUDIT_EDITOR_B_TOKEN');
  const res = await request.patch(`${API}/datasets/${datasetId}/`, {
    headers: {
      Authorization: `Bearer ${tokenB}`,
      'Content-Type': 'application/json',
    },
    data: { title: 'sec-audit-S02-attempt' },
  });
  expect([401, 403, 404]).toContain(res.status());
});

test('S02 IDOR — editor B cannot DELETE another user\'s private dataset', async ({ request }) => {
  const datasetId = process.env.SEC_AUDIT_PRIVATE_DATASET_ID;
  const tokenB = process.env.SEC_AUDIT_EDITOR_B_TOKEN;
  test.skip(!datasetId || !tokenB, 'Set SEC_AUDIT_PRIVATE_DATASET_ID and SEC_AUDIT_EDITOR_B_TOKEN');
  const res = await request.delete(`${API}/datasets/${datasetId}/`, {
    headers: { Authorization: `Bearer ${tokenB}` },
  });
  expect([401, 403, 404]).toContain(res.status());
});

test('S02 IDOR — editor B cannot bulk-delete another user\'s private dataset', async ({ request }) => {
  const datasetId = process.env.SEC_AUDIT_PRIVATE_DATASET_ID;
  const tokenB = process.env.SEC_AUDIT_EDITOR_B_TOKEN;
  test.skip(!datasetId || !tokenB, 'Set SEC_AUDIT_PRIVATE_DATASET_ID and SEC_AUDIT_EDITOR_B_TOKEN');
  const res = await request.post(`${API}/datasets/bulk-delete/`, {
    headers: {
      Authorization: `Bearer ${tokenB}`,
      'Content-Type': 'application/json',
    },
    data: { dataset_ids: [datasetId] },
  });
  // Either fully rejected (403/401) OR succeeds with a per-id failure (200/207 with deleted=0)
  if (res.status() === 200 || res.status() === 207) {
    const body = await res.json();
    const deleted = body.deleted ?? body.deleted_ids ?? [];
    expect(deleted).not.toContain(datasetId);
  } else {
    expect([401, 403, 404]).toContain(res.status());
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// S03 — Column DDL IDOR — editor B drops column on user A's private dataset
// ─────────────────────────────────────────────────────────────────────────────

test('S03 IDOR — editor B cannot add a column to another user\'s private dataset', async ({ request }) => {
  const datasetId = process.env.SEC_AUDIT_PRIVATE_DATASET_ID;
  const tokenB = process.env.SEC_AUDIT_EDITOR_B_TOKEN;
  test.skip(!datasetId || !tokenB, 'Set SEC_AUDIT_PRIVATE_DATASET_ID and SEC_AUDIT_EDITOR_B_TOKEN');
  const res = await request.post(`${API}/datasets/${datasetId}/columns/`, {
    headers: {
      Authorization: `Bearer ${tokenB}`,
      'Content-Type': 'application/json',
    },
    data: { name: 'sec_audit_S03', type: 'text' },
  });
  expect([401, 403, 404]).toContain(res.status());
});

test('S03 IDOR — editor B cannot DROP a column on another user\'s private dataset', async ({ request }) => {
  const datasetId = process.env.SEC_AUDIT_PRIVATE_DATASET_ID;
  const tokenB = process.env.SEC_AUDIT_EDITOR_B_TOKEN;
  test.skip(!datasetId || !tokenB, 'Set SEC_AUDIT_PRIVATE_DATASET_ID and SEC_AUDIT_EDITOR_B_TOKEN');
  // Use a column name that almost certainly exists on a default ingested table
  const res = await request.delete(`${API}/datasets/${datasetId}/columns/gid`, {
    headers: { Authorization: `Bearer ${tokenB}` },
  });
  expect([401, 403, 404]).toContain(res.status());
});

// ─────────────────────────────────────────────────────────────────────────────
// S04 — SSRF redirect bypass on external source connectors
// ─────────────────────────────────────────────────────────────────────────────

test('S04 SSRF — /sources/probe/ rejects redirect target to private IP', async ({ request }) => {
  const tokenA = process.env.SEC_AUDIT_EDITOR_A_TOKEN;
  const redirector = process.env.SEC_AUDIT_SSRF_TEST_REDIRECTOR;
  test.skip(!tokenA || !redirector, 'Set SEC_AUDIT_EDITOR_A_TOKEN and SEC_AUDIT_SSRF_TEST_REDIRECTOR (a URL that 302s to 169.254.169.254)');
  const res = await request.post(`${API}/sources/probe/`, {
    headers: {
      Authorization: `Bearer ${tokenA}`,
      'Content-Type': 'application/json',
    },
    data: { url: redirector },
  });
  if (res.status() === 200) {
    const body = await res.text();
    // Must not have followed redirect to IMDS / private host
    expect(body).not.toMatch(/169\.254\.169\.254|iam\/security-credentials|instance-identity/i);
    expect(body).not.toMatch(/listen_addresses|pg_hba|PostgreSQL/i);
  } else {
    expect([400, 403, 422]).toContain(res.status());
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// S05 — pgvector /datasets/{id}/related/ visibility bypass
// ─────────────────────────────────────────────────────────────────────────────

test('S05 VEC-IDOR — anonymous /related/ on a private dataset returns no oracle', async ({ request }) => {
  const datasetId = process.env.SEC_AUDIT_PRIVATE_DATASET_ID;
  test.skip(!datasetId, 'Set SEC_AUDIT_PRIVATE_DATASET_ID');
  const res = await request.get(`${API}/datasets/${datasetId}/related/`);
  // After fix: 401/403/404. Before fix: 200 with empty or partial list (oracle).
  // Empty 200 is also accepted as long as no similarity scores leak.
  if (res.status() === 200) {
    const body = await res.json();
    const items = Array.isArray(body) ? body : (body.items ?? []);
    expect(items.length).toBe(0);
  } else {
    expect([401, 403, 404]).toContain(res.status());
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// S06 — Demo credentials not accepted by default
// ─────────────────────────────────────────────────────────────────────────────

test('S06 — admin user with known-public password "demodemo" cannot log in', async ({ request }) => {
  const res = await request.post(`${API}/auth/login/`, {
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    form: { username: 'admin', password: 'demodemo' },
  });
  expect([400, 401]).toContain(res.status());
});

// ─────────────────────────────────────────────────────────────────────────────
// S08 — Embed-token framing (after fix: per-token frame-ancestors CSP exists)
// ─────────────────────────────────────────────────────────────────────────────

test('S08 — /m/<share_token> HTML response has frame-ancestors CSP (or is admin-restricted)', async ({ request }) => {
  const shareToken = process.env.SEC_AUDIT_SHARE_TOKEN;
  test.skip(!shareToken, 'Set SEC_AUDIT_SHARE_TOKEN to a public share token');
  // The frontend host serves /m/* — derive from API base
  const frontendBase = process.env.SEC_AUDIT_FRONTEND_URL || 'http://localhost:8080';
  const res = await request.get(`${frontendBase}/m/${shareToken}?embed=true`, {
    headers: { Accept: 'text/html' },
  });
  if (res.status() === 200) {
    // After S08 fix: either CSP frame-ancestors carries the embed-token's allowed_origins,
    // or the response is admin-only (no public embed). DENY/SAMEORIGIN with no CSP is the pre-fix state.
    const csp = res.headers()['content-security-policy'] || '';
    const xfo = res.headers()['x-frame-options'] || '';
    const hasFrameAncestors = csp.includes('frame-ancestors');
    const isRestrictive = ['DENY', 'SAMEORIGIN'].includes(xfo.toUpperCase());
    // Fail only the pre-fix state: SAMEORIGIN+no CSP frame-ancestors (= product contradiction)
    expect(hasFrameAncestors || !isRestrictive).toBe(true);
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// S09 — ogr2ogr -where parser rejects SQL grammar (UNION, subqueries)
// ─────────────────────────────────────────────────────────────────────────────

test('S09 — dataset export -where rejects UNION / subqueries', async ({ request }) => {
  const datasetId = process.env.SEC_AUDIT_PUBLIC_DATASET_ID;
  test.skip(!datasetId, 'Set SEC_AUDIT_PUBLIC_DATASET_ID to a public exportable dataset');
  const malicious = `gid > 0 UNION SELECT 1, 2, 3`;
  const res = await request.get(`${API}/datasets/${datasetId}/export.csv?where=${encodeURIComponent(malicious)}`);
  expect([400, 422, 403]).toContain(res.status());
});

// ─────────────────────────────────────────────────────────────────────────────
// S11 — Per-route rate limiting on semantic search
// ─────────────────────────────────────────────────────────────────────────────

test('S11 — burst of unique semantic queries gets rate-limited', async ({ request }) => {
  // Send 80 unique queries; with a 30/min per-route limit we should see 429s.
  // With only the 60/sec global limit and unique strings, all 80 pass.
  // After fix this becomes a regression pin for the per-route decorator.
  const responses = await Promise.all(
    Array.from({ length: 80 }, (_, i) =>
      request.get(`${API}/search/datasets/?q=sec-audit-S11-unique-token-${i}`)
    ),
  );
  const statuses = responses.map(r => r.status());
  const has429 = statuses.includes(429);
  // Until S11 ships, allow this to be informational — skip if no 429 observed
  test.skip(!has429, 'Per-route rate limit not yet shipped (S11 follow-up)');
  expect(has429).toBe(true);
});

// ─────────────────────────────────────────────────────────────────────────────
// S13 — /search/facets/ rejects oversized q
// ─────────────────────────────────────────────────────────────────────────────

test('S13 — /search/facets/ rejects q longer than 1000 chars', async ({ request }) => {
  const longQ = 'a'.repeat(5000);
  const res = await request.get(`${API}/search/facets/?q=${encodeURIComponent(longQ)}`);
  // After fix: 422 (Pydantic validation). Pre-fix: 200 with seq-scan.
  expect([400, 422]).toContain(res.status());
});

// ─────────────────────────────────────────────────────────────────────────────
// Hygiene regression — ensure SQL injection sentinels remain blocked
// ─────────────────────────────────────────────────────────────────────────────

test('hygiene — SQLi sentinel in search q does not crash or return all rows', async ({ request }) => {
  const res = await request.get(`${API}/search/datasets/?q=` + encodeURIComponent(`' OR '1'='1`));
  expect([200, 400, 422]).toContain(res.status());
  if (res.status() === 200) {
    const body = await res.json();
    const features = body.features ?? [];
    // Sentinel should match nothing; ensure response is bounded (LIMIT 200 cap)
    expect(features.length).toBeLessThanOrEqual(200);
  }
});

test('hygiene — pgvector embedding never appears in search response', async ({ request }) => {
  const res = await request.get(`${API}/search/datasets/?q=test`);
  if (res.status() === 200) {
    const body = await res.json();
    const features = body.features ?? [];
    for (const f of features) {
      expect(f.embedding).toBeUndefined();
      expect(f.vector).toBeUndefined();
      expect(f.properties?.embedding).toBeUndefined();
      expect(f.properties?.vector).toBeUndefined();
    }
  }
});

test('hygiene — pg_trgm operator-abuse handled safely (no syntax error, fast response)', async ({ request }) => {
  const malicious = '! | !';
  const start = Date.now();
  const res = await request.get(`${API}/search/datasets/?q=${encodeURIComponent(malicious)}`);
  const elapsed = Date.now() - start;
  expect(elapsed).toBeLessThan(3000);
  expect([200, 400, 422]).toContain(res.status());
});

test('hygiene — malformed bbox is rejected', async ({ request }) => {
  const res = await request.get(`${API}/search/datasets/?bbox=0,0,1`);
  expect([400, 422]).toContain(res.status());
});

test('hygiene — CORS allow_origins=* is never reflected', async ({ request }) => {
  // No Origin header → no CORS headers
  const res = await request.get(`${API}/`, {
    headers: { Origin: 'http://attacker.example' },
  });
  const acao = res.headers()['access-control-allow-origin'];
  // Should NOT echo a non-allowlisted origin and never be `*` with credentials
  if (acao) {
    expect(acao).not.toBe('*');
    expect(acao).not.toBe('http://attacker.example');
  }
});
