// Security regression tests — auto-generated by /sec-audit (2026-05-19)
//
// Run: npx playwright test e2e/sec-audit.spec.ts --project=chromium
//
// fix(#1778): S01/S02/S03/S05/S08/S09 used to read hand-provisioned env vars
// (SEC_AUDIT_PRIVATE_DATASET_ID etc.) that nothing in CI ever set, so those
// tests skipped on every run and the file reported green while covering 8
// of 19 cases. beforeAll below seeds the same fixtures in-spec instead, the
// way e2e/auth.setup.ts seeds a shared dataset and e2e/auth.spec.ts creates
// its throwaway e2e-logout-probe user.
//
// S04 (SSRF redirect bypass) is the one case left out: it needs a live
// external URL that 302-redirects to 169.254.169.254, which cannot be
// provisioned safely in CI. That behavior is covered by
// backend/tests/test_ssrf_redirect.py, so the test is removed below rather
// than left permanently skipped — see the comment where it used to be.
//
//   SEC_AUDIT_API_URL         override the API base (default /api)
//   SEC_AUDIT_FRONTEND_URL    override the frontend base for S08 (default E2E_BASE_URL)

import { test, expect } from '@playwright/test';
import { getAuthToken, seedDataset, seedDemDataset, deleteDataset } from './helpers/catalog';

const API = process.env.SEC_AUDIT_API_URL || '/api';
const BASE_URL = process.env.E2E_BASE_URL ?? 'http://localhost:8080';

let privateDatasetId = '';
let privateDatasetTitle = '';
let privateRasterId = '';
let privateRasterTitle = '';
let publicDatasetId = '';
let publicDatasetTitle = '';
let editorBToken = '';
let editorBUserId = '';
let shareToken = '';
let shareMapId = '';

function adminHeaders(): Record<string, string> {
  return {
    Authorization: `Bearer ${getAuthToken()}`,
    'Content-Type': 'application/json',
  };
}

test.beforeAll(async () => {
  const headers = adminHeaders();

  // S01: private, published raster. The STAC /stac/items/{id} endpoint uses
  // Dataset.id as the item id (backend/tests/test_stac_visibility.py), and
  // ingest defaults a new dataset to visibility=private, record_status=published.
  const raster = await seedDemDataset();
  privateRasterId = raster.id;
  privateRasterTitle = raster.title;

  // S02/S03/S05: private vector dataset owned by the seeding admin account.
  const priv = await seedDataset('Sec Audit Private');
  privateDatasetId = priv.id;
  privateDatasetTitle = priv.title;

  // S09: public, published vector dataset.
  const pub = await seedDataset('Sec Audit Public');
  publicDatasetId = pub.id;
  publicDatasetTitle = pub.title;
  const publishRes = await fetch(`${BASE_URL}/api/datasets/${publicDatasetId}`, {
    method: 'PATCH',
    headers,
    body: JSON.stringify({ visibility: 'public', record_status: 'published' }),
  });
  if (!publishRes.ok) {
    throw new Error(`sec-audit: could not publish public dataset: ${publishRes.status}`);
  }

  // S02/S03: a second, non-admin editor who owns neither dataset above.
  const editorBUsername = `sec-audit-editor-b-${Date.now()}`;
  const editorBPassword = 'Sec-Audit-Editor-B-42';
  const createUserRes = await fetch(`${BASE_URL}/api/admin/users/`, {
    method: 'POST',
    headers,
    body: JSON.stringify({ username: editorBUsername, password: editorBPassword, role: 'editor' }),
  });
  if (!createUserRes.ok) {
    throw new Error(`sec-audit: could not create editor B: ${createUserRes.status}`);
  }
  editorBUserId = ((await createUserRes.json()) as { id: string }).id;

  const loginRes = await fetch(`${BASE_URL}/api/auth/login/`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: new URLSearchParams({ username: editorBUsername, password: editorBPassword }).toString(),
  });
  if (!loginRes.ok) {
    throw new Error(`sec-audit: could not log in editor B: ${loginRes.status}`);
  }
  editorBToken = ((await loginRes.json()) as { access_token: string }).access_token;

  // S08: a public map with a share token.
  const mapRes = await fetch(`${BASE_URL}/api/maps/`, {
    method: 'POST',
    headers,
    body: JSON.stringify({ name: `Sec Audit Share Map ${Date.now()}` }),
  });
  if (!mapRes.ok) {
    throw new Error(`sec-audit: could not create share map: ${mapRes.status}`);
  }
  shareMapId = ((await mapRes.json()) as { id: string }).id;
  const mapPublishRes = await fetch(`${BASE_URL}/api/maps/${shareMapId}`, {
    method: 'PUT',
    headers,
    body: JSON.stringify({ visibility: 'public' }),
  });
  if (!mapPublishRes.ok) {
    throw new Error(`sec-audit: could not publish share map: ${mapPublishRes.status}`);
  }
  const shareRes = await fetch(`${BASE_URL}/api/maps/${shareMapId}/share/`, {
    method: 'POST',
    headers,
  });
  if (!shareRes.ok) {
    throw new Error(`sec-audit: could not create share token: ${shareRes.status}`);
  }
  shareToken = ((await shareRes.json()) as { token: string }).token;
});

test.afterAll(async () => {
  const headers = adminHeaders();
  if (shareMapId) {
    await fetch(`${BASE_URL}/api/maps/${shareMapId}`, { method: 'DELETE', headers }).catch(() => {});
  }
  if (editorBUserId) {
    await fetch(`${BASE_URL}/api/admin/users/${editorBUserId}`, { method: 'DELETE', headers }).catch(() => {});
  }
  if (privateDatasetId) await deleteDataset(privateDatasetId, privateDatasetTitle);
  if (publicDatasetId) await deleteDataset(publicDatasetId, publicDatasetTitle);
  if (privateRasterId) await deleteDataset(privateRasterId, privateRasterTitle);
});

// ─────────────────────────────────────────────────────────────────────────────
// S01 — STAC visibility bypass (anonymous read of private raster)
// ─────────────────────────────────────────────────────────────────────────────

test('S01 STAC visibility — anonymous cannot read a private raster STAC item', async ({ request }) => {
  const recordId = privateRasterId;
  const res = await request.get(`${API}/stac/items/${recordId}`);
  expect([401, 403, 404]).toContain(res.status());
});

test('S01 STAC visibility — anonymous /stac/search does not return private rasters', async ({ request }) => {
  const recordId = privateRasterId;
  const res = await request.get(`${API}/stac/search?ids=${recordId}`);
  // Either denied (401/403) or empty features list — never the private item back
  if (res.status() === 200) {
    const body = await res.json();
    const features = body.features ?? [];
    const hit = features.find((f: { id: string }) => f.id === recordId);
    expect(hit).toBeUndefined();
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// S02 — Dataset metadata IDOR — editor B mutates user A's private dataset
// ─────────────────────────────────────────────────────────────────────────────

test('S02 IDOR — editor B cannot PATCH another user\'s private dataset', async ({ request }) => {
  const datasetId = privateDatasetId;
  const tokenB = editorBToken;
  const res = await request.patch(`${API}/datasets/${datasetId}/`, {
    headers: {
      Authorization: `Bearer ${tokenB}`,
      'Content-Type': 'application/json',
    },
    data: { title: 'sec-audit-S02-attempt' },
  });
  expect([401, 403, 404]).toContain(res.status());
});

test('S02 IDOR — editor B cannot DELETE another user\'s private dataset', async ({ request }) => {
  const datasetId = privateDatasetId;
  const tokenB = editorBToken;
  const res = await request.delete(`${API}/datasets/${datasetId}/`, {
    headers: { Authorization: `Bearer ${tokenB}` },
  });
  expect([401, 403, 404]).toContain(res.status());
});

test('S02 IDOR — editor B cannot bulk-delete another user\'s private dataset', async ({ request }) => {
  const datasetId = privateDatasetId;
  const tokenB = editorBToken;
  // fix(#1778): BulkDeleteRequest's schema is `{ datasets: [{ dataset_id,
  // confirm_title }] }` (backend/openapi.json), not `{ dataset_ids: [...] }`
  // — the old payload always 422'd before authorization was ever reached,
  // which the permanent skip guard hid. bulk_delete_datasets_endpoint
  // (router.py) isolates per-item failures rather than rejecting the whole
  // batch, so a denied item surfaces as HTTP 200 with a per-item
  // status: 'error', never a top-level 401/403/404.
  const res = await request.post(`${API}/datasets/bulk-delete/`, {
    headers: {
      Authorization: `Bearer ${tokenB}`,
      'Content-Type': 'application/json',
    },
    data: { datasets: [{ dataset_id: datasetId, confirm_title: privateDatasetTitle }] },
  });
  expect(res.status()).toBe(200);
  const body = await res.json();
  const results = body.results ?? [];
  const item = results.find((r: { dataset_id: string }) => r.dataset_id === datasetId);
  expect(item?.status).not.toBe('deleted');
});

// ─────────────────────────────────────────────────────────────────────────────
// S03 — Column DDL IDOR — editor B drops column on user A's private dataset
// ─────────────────────────────────────────────────────────────────────────────

test('S03 IDOR — editor B cannot add a column to another user\'s private dataset', async ({ request }) => {
  const datasetId = privateDatasetId;
  const tokenB = editorBToken;
  const res = await request.post(`${API}/datasets/${datasetId}/columns/`, {
    headers: {
      Authorization: `Bearer ${tokenB}`,
      'Content-Type': 'application/json',
    },
    data: { name: 'sec_audit_S03', type: 'text' },
  });
  expect([401, 403, 404]).toContain(res.status());
});

test('S03 IDOR — editor B cannot DROP a column on another user\'s private dataset', async ({ request }) => {
  const datasetId = privateDatasetId;
  const tokenB = editorBToken;
  // Use a column name that almost certainly exists on a default ingested table
  const res = await request.delete(`${API}/datasets/${datasetId}/columns/gid`, {
    headers: { Authorization: `Bearer ${tokenB}` },
  });
  expect([401, 403, 404]).toContain(res.status());
});

// ─────────────────────────────────────────────────────────────────────────────
// S04 — SSRF redirect bypass on external source connectors
//
// fix(#1778): removed rather than left permanently skipped. This test needs
// a live external URL that 302-redirects to 169.254.169.254; CI has no such
// endpoint and standing one up is a real infrastructure dependency, not a
// fixture this spec can seed. The redirect-revalidation behavior itself is
// covered by backend/tests/test_ssrf_redirect.py, which mocks the redirect.
// ─────────────────────────────────────────────────────────────────────────────

// ─────────────────────────────────────────────────────────────────────────────
// S05 — pgvector /datasets/{id}/related/ visibility bypass
// ─────────────────────────────────────────────────────────────────────────────

test('S05 VEC-IDOR — anonymous /related/ on a private dataset returns no oracle', async ({ request }) => {
  const datasetId = privateDatasetId;
  const res = await request.get(`${API}/datasets/${datasetId}/related/`);
  // After fix: 401/403/404. Before fix: 200 with empty or partial list (oracle).
  // Empty 200 is also accepted as long as no similarity scores leak.
  if (res.status() === 200) {
    const body = await res.json();
    const items = Array.isArray(body) ? body : (body.items ?? []);
    expect(items.length).toBe(0);
  } else {
    expect([401, 403, 404]).toContain(res.status());
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// S06 — Demo credentials not accepted by default
// ─────────────────────────────────────────────────────────────────────────────

test('S06 — admin user with known-public password "demodemo" cannot log in', async ({ request }) => {
  const res = await request.post(`${API}/auth/login/`, {
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    form: { username: 'admin', password: 'demodemo' },
  });
  expect([400, 401]).toContain(res.status());
});

// ─────────────────────────────────────────────────────────────────────────────
// S08 — Embed-token framing (after fix: per-token frame-ancestors CSP exists)
// ─────────────────────────────────────────────────────────────────────────────

test('S08 — /m/<share_token> HTML response has frame-ancestors CSP (or is admin-restricted)', async ({ request }) => {
  // The frontend host serves /m/* — derive from API base
  const frontendBase = process.env.SEC_AUDIT_FRONTEND_URL || 'http://localhost:8080';
  const res = await request.get(`${frontendBase}/m/${shareToken}?embed=true`, {
    headers: { Accept: 'text/html' },
  });
  if (res.status() === 200) {
    // After S08 fix: either CSP frame-ancestors carries the embed-token's allowed_origins,
    // or the response is admin-only (no public embed). DENY/SAMEORIGIN with no CSP is the pre-fix state.
    const csp = res.headers()['content-security-policy'] || '';
    const xfo = res.headers()['x-frame-options'] || '';
    const hasFrameAncestors = csp.includes('frame-ancestors');
    const isRestrictive = ['DENY', 'SAMEORIGIN'].includes(xfo.toUpperCase());
    // Fail only the pre-fix state: SAMEORIGIN+no CSP frame-ancestors (= product contradiction)
    expect(hasFrameAncestors || !isRestrictive).toBe(true);
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// S09 — ogr2ogr -where parser rejects SQL grammar (UNION, subqueries)
// ─────────────────────────────────────────────────────────────────────────────

test('S09 — dataset export -where rejects UNION / subqueries', async ({ request }) => {
  const datasetId = publicDatasetId;
  const malicious = `gid > 0 UNION SELECT 1, 2, 3`;
  // fix(#1778): the export route is /datasets/{id}/export?format=csv, not
  // /datasets/{id}/export.csv (backend/openapi.json has no such path) — the
  // old URL always 404'd before the -where parser ever ran, which the
  // permanent skip guard hid.
  const res = await request.get(
    `${API}/datasets/${datasetId}/export?format=csv&where=${encodeURIComponent(malicious)}`,
  );
  expect([400, 422, 403]).toContain(res.status());
});

// ─────────────────────────────────────────────────────────────────────────────
// S11 — Per-route rate limiting on semantic search
// ─────────────────────────────────────────────────────────────────────────────

test('S11 — burst of unique semantic queries gets rate-limited', async ({ request }) => {
  // Send 80 unique queries; with a 30/min per-route limit we should see 429s.
  // With only the 60/sec global limit and unique strings, all 80 pass.
  // After fix this becomes a regression pin for the per-route decorator.
  const responses = await Promise.all(
    Array.from({ length: 80 }, (_, i) =>
      request.get(`${API}/search/datasets/?q=sec-audit-S11-unique-token-${i}`)
    ),
  );
  const statuses = responses.map(r => r.status());
  const has429 = statuses.includes(429);
  // fix(#1778): the skip guard fired on exactly the outcome this test exists
  // to catch, so it could never go red. The per-route decorator has shipped
  // (search/router.py's search_datasets_endpoint carries
  // @limiter.limit(_semantic_search_rate_limit), default 30/minute) — gate on it.
  expect(has429).toBe(true);
});

// ─────────────────────────────────────────────────────────────────────────────
// S13 — /search/facets/ rejects oversized q
// ─────────────────────────────────────────────────────────────────────────────

test('S13 — /search/facets/ rejects q longer than 1000 chars', async ({ request }) => {
  const longQ = 'a'.repeat(5000);
  const res = await request.get(`${API}/search/facets/?q=${encodeURIComponent(longQ)}`);
  // After fix: 422 (Pydantic validation). Pre-fix: 200 with seq-scan.
  // 429: the S11 burst test above can leave the per-IP rate limiter saturated
  // within the same window — a safe rejection still satisfies this hygiene check.
  expect([400, 422, 429]).toContain(res.status());
});

// ─────────────────────────────────────────────────────────────────────────────
// Hygiene regression — ensure SQL injection sentinels remain blocked
// ─────────────────────────────────────────────────────────────────────────────

test('hygiene — SQLi sentinel in search q does not crash or return all rows', async ({ request }) => {
  const res = await request.get(`${API}/search/datasets/?q=` + encodeURIComponent(`' OR '1'='1`));
  expect([200, 400, 422, 429]).toContain(res.status()); // 429: safe rate-limit rejection (S11 burst bleed)
  if (res.status() === 200) {
    const body = await res.json();
    const features = body.features ?? [];
    // Sentinel should match nothing; ensure response is bounded (LIMIT 200 cap)
    expect(features.length).toBeLessThanOrEqual(200);
  }
});

test('hygiene — pgvector embedding never appears in search response', async ({ request }) => {
  const res = await request.get(`${API}/search/datasets/?q=test`);
  if (res.status() === 200) {
    const body = await res.json();
    const features = body.features ?? [];
    for (const f of features) {
      expect(f.embedding).toBeUndefined();
      expect(f.vector).toBeUndefined();
      expect(f.properties?.embedding).toBeUndefined();
      expect(f.properties?.vector).toBeUndefined();
    }
  }
});

test('hygiene — pg_trgm operator-abuse handled safely (no syntax error, fast response)', async ({ request }) => {
  const malicious = '! | !';
  const start = Date.now();
  const res = await request.get(`${API}/search/datasets/?q=${encodeURIComponent(malicious)}`);
  const elapsed = Date.now() - start;
  expect(elapsed).toBeLessThan(3000);
  expect([200, 400, 422, 429]).toContain(res.status()); // 429: safe rate-limit rejection (S11 burst bleed)
});

test('hygiene — malformed bbox is rejected', async ({ request }) => {
  const res = await request.get(`${API}/search/datasets/?bbox=0,0,1`);
  expect([400, 422, 429]).toContain(res.status()); // 429: safe rate-limit rejection (S11 burst bleed)
});

test('hygiene — CORS does not grant credentials to an untrusted origin', async ({ request }) => {
  const origin = 'http://attacker.example';
  const appResponse = await request.get(`${API}/auth/me/`, {
    headers: { Origin: origin },
  });
  expect(appResponse.headers()['access-control-allow-origin']).toBeUndefined();
  expect(appResponse.headers()['access-control-allow-credentials']).toBeUndefined();

  // Anonymous standards routes may use a wildcard, but never with credentials.
  const standardsResponse = await request.get(`${API}/`, {
    headers: { Origin: 'http://attacker.example' },
  });
  const standardsOrigin = standardsResponse.headers()['access-control-allow-origin'];
  expect(standardsOrigin).not.toBe(origin);
  if (standardsOrigin === '*') {
    expect(
      standardsResponse.headers()['access-control-allow-credentials'],
    ).toBeUndefined();
  }
});
