"""Create all application tables.

Auto-generated from SQLAlchemy models, then manually adjusted.

Revision ID: 0002_tbl
Revises: 0001_fdn
Create Date: 2026-03-28
"""
from typing import Sequence, Union

from alembic import op
import geoalchemy2  # noqa: F401 -- registers Geometry type
import pgvector.sqlalchemy.vector  # noqa: F401 -- registers VECTOR type
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "0002_tbl"
down_revision: Union[str, None] = "0001_fdn"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('key'),
    schema='catalog'
    )
    op.create_table('oauth_providers',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('provider_type', sa.String(length=20), nullable=False),
    sa.Column('client_id', sa.String(length=512), nullable=False),
    sa.Column('client_secret_encrypted', sa.Text(), nullable=False),
    sa.Column('discovery_url', sa.String(length=512), nullable=True),
    sa.Column('authorize_url', sa.String(length=512), nullable=True),
    sa.Column('token_url', sa.String(length=512), nullable=True),
    sa.Column('userinfo_url', sa.String(length=512), nullable=True),
    sa.Column('scopes', sa.String(length=512), server_default='openid profile email', nullable=False),
    sa.Column('default_role', sa.String(length=50), server_default='viewer', nullable=False),
    sa.Column('group_claim', sa.String(length=100), nullable=True),
    sa.Column('group_role_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('idp_entity_id', sa.String(length=512), nullable=True),
    sa.Column('idp_sso_url', sa.String(length=512), nullable=True),
    sa.Column('idp_certificate', sa.Text(), nullable=True),
    sa.Column('sp_entity_id', sa.String(length=512), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("provider_type IN ('oidc', 'google', 'microsoft', 'saml')", name='chk_oauth_providers_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    schema='catalog'
    )
    op.create_table('roles',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='catalog'
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('auth_provider', sa.String(length=20), server_default='local', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("auth_provider IN ('local', 'oidc', 'saml', 'oauth')", name='chk_users_auth_provider'),
    sa.CheckConstraint("status IN ('active', 'pending', 'suspended', 'deactivated')", name='chk_users_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    schema='catalog'
    )
    op.create_table('api_keys',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['catalog.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash'),
    schema='catalog'
    )
    op.create_index(op.f('ix_catalog_api_keys_user_id'), 'api_keys', ['user_id'], unique=False, schema='catalog')
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['catalog.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='catalog'
    )
    op.create_table('collections',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['catalog.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='catalog'
    )
    op.create_table('maps',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('center_lng', sa.Float(), nullable=True),
    sa.Column('center_lat', sa.Float(), nullable=True),
    sa.Column('zoom', sa.Float(), nullable=True),
    sa.Column('bearing', sa.Float(), server_default='0', nullable=False),
    sa.Column('pitch', sa.Float(), server_default='0', nullable=False),
    sa.Column('basemap_style', sa.String(length=30), server_default='openfreemap-positron', nullable=False),
    sa.Column('visibility', sa.String(length=20), server_default='private', nullable=False),
    sa.Column('thumbnail_uri', sa.Text(), nullable=True),
    sa.Column('forked_from', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("visibility IN ('private', 'public', 'internal', 'unlisted')", name='chk_maps_visibility'),
    sa.ForeignKeyConstraint(['created_by'], ['catalog.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['forked_from'], ['catalog.maps.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='catalog'
    )
    op.create_index(op.f('ix_catalog_maps_created_by'), 'maps', ['created_by'], unique=False, schema='catalog')
    op.create_table('oauth_accounts',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['catalog.oauth_providers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['catalog.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'subject', name='uq_oauth_account_provider_subject'),
    schema='catalog'
    )
    op.create_index(op.f('ix_catalog_oauth_accounts_user_id'), 'oauth_accounts', ['user_id'], unique=False, schema='catalog')
    op.create_table('records',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('license', sa.Text(), nullable=True),
    sa.Column('source_organization', sa.Text(), nullable=True),
    sa.Column('owner_org', sa.Text(), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('record_status', sa.String(length=20), nullable=False),
    sa.Column('record_type', sa.String(length=20), server_default='vector_dataset', nullable=False),
    sa.Column('spatial_extent', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('temporal_start', sa.Date(), nullable=True),
    sa.Column('temporal_end', sa.Date(), nullable=True),
    sa.Column('lineage_summary', sa.Text(), nullable=True),
    sa.Column('update_frequency', sa.String(length=30), nullable=True),
    sa.Column('usage_constraints', sa.Text(), nullable=True),
    sa.Column('access_constraints', sa.Text(), nullable=True),
    sa.Column('sensitivity_classification', sa.String(length=20), nullable=True),
    sa.Column('theme_category', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("setweight(to_tsvector('english'::regconfig, coalesce(title, '')), 'A') || setweight(to_tsvector('english'::regconfig, coalesce(summary, '')), 'B') || setweight(to_tsvector('english'::regconfig, coalesce(lineage_summary, '')), 'C') || setweight(to_tsvector('english'::regconfig, coalesce(catalog.immutable_array_camel_to_spaced(theme_category, ' '), '')), 'B')", persisted=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("record_status IN ('draft', 'ready', 'internal', 'published')", name='chk_records_record_status'),
    sa.CheckConstraint("record_type IN ('vector_dataset', 'raster_dataset', 'vrt_dataset', 'map', 'service', 'collection', 'table')", name='chk_records_record_type'),
    sa.CheckConstraint("sensitivity_classification IS NULL OR sensitivity_classification IN ('public', 'internal', 'confidential', 'restricted')", name='chk_records_sensitivity'),
    sa.CheckConstraint("update_frequency IS NULL OR update_frequency IN ('continual', 'daily', 'weekly', 'monthly', 'quarterly', 'biannually', 'annually', 'asNeeded', 'irregular', 'notPlanned', 'unknown')", name='chk_records_update_frequency'),
    sa.CheckConstraint("visibility IN ('public', 'private', 'internal', 'restricted')", name='chk_records_visibility'),
    sa.CheckConstraint('temporal_start IS NULL OR temporal_end IS NULL OR temporal_start <= temporal_end', name='chk_temporal_ordering'),
    sa.ForeignKeyConstraint(['created_by'], ['catalog.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['catalog.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='catalog'
    )
    op.create_index('idx_records_created_at_desc', 'records', ['created_at'], unique=False, schema='catalog', postgresql_using='btree')
    op.create_index('idx_records_source_organization', 'records', ['source_organization'], unique=False, schema='catalog', postgresql_where='source_organization IS NOT NULL')
    # idx_records_spatial_extent created automatically by GeoAlchemy2
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['catalog.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash'),
    schema='catalog'
    )
    op.create_table('saved_searches',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['catalog.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_saved_searches_user_name'),
    schema='catalog'
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['catalog.roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['catalog.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    schema='catalog'
    )
    op.create_table('dataset_relationships',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_dataset_id', sa.Uuid(), nullable=False),
    sa.Column('target_dataset_id', sa.Uuid(), nullable=False),
    sa.Column('source_column', sa.String(length=100), nullable=False),
    sa.Column('target_column', sa.String(length=100), server_default='gid', nullable=False),
    sa.Column('relationship_type', sa.String(length=20), server_default='foreign_key', nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_dataset_id'], ['catalog.records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_dataset_id'], ['catalog.records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_dataset_id', 'target_dataset_id', 'source_column', name='uq_dataset_relationship'),
    schema='catalog'
    )
    op.create_table('datasets',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('record_id', sa.Uuid(), nullable=False),
    sa.Column('table_name', sa.String(length=255), nullable=False),
    sa.Column('srid', sa.Integer(), nullable=True),
    sa.Column('geometry_type', sa.String(length=50), nullable=True),
    sa.Column('feature_count', sa.BigInteger(), nullable=True),
    sa.Column('column_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sample_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('quality_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('quality_statement', sa.Text(), nullable=True),
    sa.Column('quality_score_numeric', sa.Float(), nullable=True),
    sa.Column('quicklook_256_uri', sa.Text(), nullable=True),
    sa.Column('source_format', sa.String(length=50), nullable=True),
    sa.Column('source_filename', sa.String(length=500), nullable=True),
    sa.Column('original_srid', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(length=2000), nullable=True),
    sa.Column('current_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('tile_cache_ttl', sa.Integer(), nullable=True),
    sa.CheckConstraint("geometry_type IS NULL OR UPPER(geometry_type) IN ('POINT', 'LINESTRING', 'POLYGON', 'MULTIPOINT', 'MULTILINESTRING', 'MULTIPOLYGON', 'GEOMETRYCOLLECTION')", name='chk_datasets_geometry_type'),
    sa.CheckConstraint("source_format IS NULL OR source_format IN ('geojson', 'shapefile', 'shp', 'gpkg', 'csv', 'kml', 'gml', 'wfs', 'arcgis_featureserver', 'fgdb', 'created', 'geotiff')", name='chk_datasets_source_format'),
    sa.CheckConstraint('original_srid IS NULL OR original_srid > 0', name='chk_datasets_original_srid_positive'),
    sa.CheckConstraint('quality_score_numeric IS NULL OR (quality_score_numeric >= 0 AND quality_score_numeric <= 1)', name='chk_quality_score_range'),
    sa.CheckConstraint('srid IS NULL OR srid > 0', name='chk_datasets_srid_positive'),
    sa.ForeignKeyConstraint(['record_id'], ['catalog.records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_id'),
    sa.UniqueConstraint('table_name'),
    schema='catalog'
    )
    op.create_table('embed_tokens',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('map_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('token_hint', sa.String(length=20), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('scoped_dataset_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('allowed_origins', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('use_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['catalog.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['map_id'], ['catalog.maps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='catalog'
    )
    op.create_index(op.f('ix_catalog_embed_tokens_map_id'), 'embed_tokens', ['map_id'], unique=False, schema='catalog')
    op.create_index(op.f('ix_catalog_embed_tokens_token_hash'), 'embed_tokens', ['token_hash'], unique=True, schema='catalog')
    op.create_index('uq_embed_tokens_one_active_per_map', 'embed_tokens', ['map_id'], unique=True, schema='catalog', postgresql_where=sa.text('is_active = true'))
    op.create_table('map_share_tokens',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('map_id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['catalog.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['map_id'], ['catalog.maps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    schema='catalog'
    )
    op.create_table('record_contacts',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('record_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('organization', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('extra_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.CheckConstraint("role IN ('resourceProvider', 'custodian', 'owner', 'user', 'distributor', 'originator', 'pointOfContact', 'principalInvestigator', 'processor', 'publisher', 'author', 'sponsor', 'coAuthor', 'collaborator', 'editor', 'mediator', 'rightsHolder', 'contributor', 'funder', 'stakeholder')", name='chk_contact_role'),
    sa.ForeignKeyConstraint(['record_id'], ['catalog.records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='catalog'
    )
    op.create_table('record_distributions',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('record_id', sa.Uuid(), nullable=False),
    sa.Column('distribution_type', sa.String(length=30), nullable=False),
    sa.Column('format', sa.String(length=50), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('protocol', sa.String(length=100), nullable=True),
    sa.Column('media_type', sa.String(length=100), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('auto_generated', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint("distribution_type IN ('download', 'api', 'ogcService', 'ogc_features', 'webApp', 'offlineAccess', 'vector_tiles')", name='chk_distribution_type'),
    sa.ForeignKeyConstraint(['record_id'], ['catalog.records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_id', 'distribution_type', 'format', 'url', name='uq_record_distribution'),
    schema='catalog'
    )
    op.create_table('record_embeddings',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('record_id', sa.Uuid(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['catalog.records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_id', 'model_name', name='uq_record_embedding_model'),
    schema='catalog'
    )
    op.create_table('record_keywords',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('record_id', sa.Uuid(), nullable=False),
    sa.Column('keyword', sa.Text(), nullable=False),
    sa.Column('vocabulary_uri', sa.Text(), nullable=True),
    sa.Column('keyword_type', sa.String(length=20), server_default='theme', nullable=False),
    sa.CheckConstraint("keyword_type IN ('discipline', 'place', 'stratum', 'temporal', 'theme', 'dataCentre', 'featureType', 'instrument', 'platform', 'process', 'product', 'project', 'service', 'subTopicCategory', 'taxon')", name='chk_keyword_type'),
    sa.ForeignKeyConstraint(['record_id'], ['catalog.records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='catalog'
    )
    # Functional unique index (COALESCE not expressible in model)
    op.execute("""
    CREATE UNIQUE INDEX uq_record_keyword ON catalog.record_keywords
        USING btree (record_id, keyword, keyword_type, COALESCE(vocabulary_uri, ''))
    """)
    op.create_table('attribute_metadata',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('data_type', sa.Text(), nullable=True),
    sa.Column('units', sa.Text(), nullable=True),
    sa.Column('domain_type', sa.String(length=20), nullable=True),
    sa.Column('semantic_role', sa.String(length=20), nullable=True),
    sa.Column('example_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ordinal_position', sa.Integer(), nullable=True),
    sa.Column('is_nullable', sa.Boolean(), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('user_modified_fields', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.CheckConstraint("domain_type IS NULL OR domain_type IN ('continuous', 'discrete', 'categorical', 'coded', 'codedValue', 'boolean', 'text', 'date', 'temporal', 'geometry', 'range')", name='chk_domain_type'),
    sa.CheckConstraint("semantic_role IS NULL OR semantic_role IN ('geometry', 'identifier', 'measure', 'temporal', 'categorical', 'category', 'label', 'foreign_key', 'other')", name='chk_semantic_role'),
    sa.ForeignKeyConstraint(['dataset_id'], ['catalog.datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'field_name', name='uq_attribute_metadata'),
    schema='catalog'
    )
    op.create_table('collection_datasets',
    sa.Column('collection_id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('added_by', sa.Uuid(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['catalog.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['collection_id'], ['catalog.collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dataset_id'], ['catalog.datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collection_id', 'dataset_id'),
    schema='catalog'
    )
    op.create_table('dataset_assets',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('href', sa.Text(), nullable=False),
    sa.Column('media_type', sa.String(length=100), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('roles', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("key IN ('data', 'vrt', 'thumbnail', 'overview', 'metadata')", name='chk_dataset_assets_key'),
    sa.ForeignKeyConstraint(['dataset_id'], ['catalog.datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'key', name='uq_dataset_assets_key'),
    schema='catalog'
    )
    op.create_table('dataset_grants',
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['catalog.datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['catalog.roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dataset_id', 'role_id'),
    schema='catalog'
    )
    op.create_table('dataset_versions',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('source_filename', sa.Text(), nullable=True),
    sa.Column('source_format', sa.Text(), nullable=True),
    sa.Column('feature_count', sa.Integer(), nullable=True),
    sa.Column('srid', sa.Integer(), nullable=True),
    sa.Column('geometry_type', sa.Text(), nullable=True),
    sa.Column('file_hash', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.Uuid(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['catalog.datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['catalog.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'version_number', name='uq_dataset_version'),
    schema='catalog'
    )
    op.create_table('ingest_jobs',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('source_filename', sa.String(length=500), nullable=True),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('source_url', sa.String(length=2000), nullable=True),
    sa.Column('source_layer', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('user_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'running', 'complete', 'failed', 'cancelled')", name='chk_ingest_jobs_status'),
    sa.ForeignKeyConstraint(['created_by'], ['catalog.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dataset_id'], ['catalog.datasets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='catalog'
    )
    op.create_index(op.f('ix_catalog_ingest_jobs_created_by'), 'ingest_jobs', ['created_by'], unique=False, schema='catalog')
    op.create_table('map_layers',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('map_id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('visible', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('opacity', sa.Float(), server_default='1.0', nullable=False),
    sa.Column('paint', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('layout', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('layer_type', sa.String(length=50), server_default='vector_geolens', nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('filter', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('label_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('style_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('show_in_legend', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("layer_type IN ('vector_geolens', 'raster_geolens', 'geojson')", name='chk_map_layers_layer_type'),
    sa.ForeignKeyConstraint(['dataset_id'], ['catalog.datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['map_id'], ['catalog.maps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='catalog'
    )
    op.create_table('raster_assets',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('asset_uri', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('driver', sa.String(length=50), nullable=True),
    sa.Column('storage_backend', sa.String(length=20), server_default='local', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_sha256', sa.String(length=64), nullable=True),
    sa.Column('cog_status', sa.String(length=20), nullable=True),
    sa.Column('quicklook_256_uri', sa.Text(), nullable=True),
    sa.Column('quicklook_512_uri', sa.Text(), nullable=True),
    sa.Column('is_rotated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('crs_wkt', sa.Text(), nullable=True),
    sa.Column('epsg', sa.Integer(), nullable=True),
    sa.Column('band_count', sa.Integer(), nullable=True),
    sa.Column('dtype', sa.String(length=30), nullable=True),
    sa.Column('nodata', sa.Text(), nullable=True),
    sa.Column('res_x', sa.Double(), nullable=True),
    sa.Column('res_y', sa.Double(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('compression', sa.String(length=30), nullable=True),
    sa.Column('band_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('vrt_type', sa.String(length=20), nullable=True),
    sa.Column('resolution_strategy', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='ready', nullable=False),
    sa.Column('current_generation_id', sa.Uuid(), nullable=True),
    sa.Column('last_regenerated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("cog_status IS NULL OR cog_status IN ('verified', 'converted', 'unknown')", name='chk_raster_assets_cog_status'),
    sa.CheckConstraint("status IN ('ready', 'regenerating', 'failed')", name='chk_raster_assets_status'),
    sa.CheckConstraint("storage_backend IN ('local', 's3')", name='chk_raster_assets_storage_backend'),
    sa.CheckConstraint("vrt_type IS NULL OR vrt_type IN ('mosaic', 'band_stack')", name='chk_raster_assets_vrt_type'),
    sa.ForeignKeyConstraint(['dataset_id'], ['catalog.datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', name='uq_raster_assets_dataset'),
    schema='catalog'
    )
    op.create_table('vrt_generations',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('vrt_dataset_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Double(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('source_count', sa.Integer(), nullable=True),
    sa.Column('triggered_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'running', 'completed', 'failed')", name='chk_vrt_generations_status'),
    sa.ForeignKeyConstraint(['vrt_dataset_id'], ['catalog.datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='catalog'
    )
    op.create_table('vrt_source_links',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('vrt_dataset_id', sa.Uuid(), nullable=False),
    sa.Column('source_dataset_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_dataset_id'], ['catalog.datasets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vrt_dataset_id'], ['catalog.datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vrt_dataset_id', 'source_dataset_id', name='uq_vsl_vrt_source'),
    schema='catalog'
    )
    op.create_index(op.f('ix_catalog_vrt_source_links_source_dataset_id'), 'vrt_source_links', ['source_dataset_id'], unique=False, schema='catalog')
    op.create_index(op.f('ix_catalog_vrt_source_links_vrt_dataset_id'), 'vrt_source_links', ['vrt_dataset_id'], unique=False, schema='catalog')

    # --- Functional/performance indexes not expressible in models ---

    # Full-text search on records
    op.execute("""
    CREATE INDEX idx_records_search_vector ON catalog.records
        USING gin (search_vector)
    """)
    # Composite filter index
    op.execute("""
    CREATE INDEX idx_records_visibility_status_creator ON catalog.records
        USING btree (visibility, record_status, created_by)
    """)
    # Full-text search on contacts
    op.execute("""
    CREATE INDEX ix_record_contacts_fts ON catalog.record_contacts
        USING gin (to_tsvector('english'::regconfig,
            COALESCE(name, '') || ' ' || COALESCE(organization, '')))
    """)
    # Full-text search on keywords
    op.execute("""
    CREATE INDEX ix_record_keywords_fts ON catalog.record_keywords
        USING gin (to_tsvector('english'::regconfig, keyword))
    """)
    # Partial index on pending users
    op.execute("""
    CREATE INDEX idx_users_status_pending ON catalog.users
        USING btree (status) WHERE status = 'pending'
    """)
    # Attribute metadata composite index
    op.execute("""
    CREATE INDEX idx_attribute_metadata_dataset_current ON catalog.attribute_metadata
        USING btree (dataset_id, is_current)
    """)

    # --- Trigger: auto-update records.updated_at ---
    op.execute("""
    CREATE TRIGGER trg_records_updated_at
        BEFORE UPDATE ON catalog.records
        FOR EACH ROW EXECUTE FUNCTION catalog.set_updated_at()
    """)


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_records_updated_at ON catalog.records")
    op.drop_index(op.f('ix_catalog_vrt_source_links_vrt_dataset_id'), table_name='vrt_source_links', schema='catalog')
    op.drop_index(op.f('ix_catalog_vrt_source_links_source_dataset_id'), table_name='vrt_source_links', schema='catalog')
    op.drop_table('vrt_source_links', schema='catalog')
    op.drop_table('vrt_generations', schema='catalog')
    op.drop_table('raster_assets', schema='catalog')
    op.drop_table('map_layers', schema='catalog')
    op.drop_index(op.f('ix_catalog_ingest_jobs_created_by'), table_name='ingest_jobs', schema='catalog')
    op.drop_table('ingest_jobs', schema='catalog')
    op.drop_table('dataset_versions', schema='catalog')
    op.drop_table('dataset_grants', schema='catalog')
    op.drop_table('dataset_assets', schema='catalog')
    op.drop_table('collection_datasets', schema='catalog')
    op.drop_table('attribute_metadata', schema='catalog')
    op.drop_table('record_keywords', schema='catalog')
    op.drop_table('record_embeddings', schema='catalog')
    op.drop_table('record_distributions', schema='catalog')
    op.drop_table('record_contacts', schema='catalog')
    op.drop_table('map_share_tokens', schema='catalog')
    op.drop_index('uq_embed_tokens_one_active_per_map', table_name='embed_tokens', schema='catalog', postgresql_where=sa.text('is_active = true'))
    op.drop_index(op.f('ix_catalog_embed_tokens_token_hash'), table_name='embed_tokens', schema='catalog')
    op.drop_index(op.f('ix_catalog_embed_tokens_map_id'), table_name='embed_tokens', schema='catalog')
    op.drop_table('embed_tokens', schema='catalog')
    op.drop_table('datasets', schema='catalog')
    op.drop_table('dataset_relationships', schema='catalog')
    op.drop_table('user_roles', schema='catalog')
    op.drop_table('saved_searches', schema='catalog')
    op.drop_table('refresh_tokens', schema='catalog')
    # idx_records_spatial_extent dropped automatically with the table (GeoAlchemy2)
    op.drop_index('idx_records_source_organization', table_name='records', schema='catalog', postgresql_where='source_organization IS NOT NULL')
    op.drop_index('idx_records_created_at_desc', table_name='records', schema='catalog', postgresql_using='btree')
    op.drop_table('records', schema='catalog')
    op.drop_index(op.f('ix_catalog_oauth_accounts_user_id'), table_name='oauth_accounts', schema='catalog')
    op.drop_table('oauth_accounts', schema='catalog')
    op.drop_index(op.f('ix_catalog_maps_created_by'), table_name='maps', schema='catalog')
    op.drop_table('maps', schema='catalog')
    op.drop_table('collections', schema='catalog')
    op.drop_table('audit_logs', schema='catalog')
    op.drop_index(op.f('ix_catalog_api_keys_user_id'), table_name='api_keys', schema='catalog')
    op.drop_table('api_keys', schema='catalog')
    op.drop_table('users', schema='catalog')
    op.drop_table('roles', schema='catalog')
    op.drop_table('oauth_providers', schema='catalog')
    op.drop_table('app_settings', schema='catalog')
    # ### end Alembic commands ###
