"""Allow 'fgb' in chk_datasets_source_format.

Tier-1 vector import adds FlatGeobuf (``.fgb``), KML/KMZ, and zipped File
Geodatabase uploads. Only FlatGeobuf needs a new constraint value:

- ``.fgb`` derives ``source_format = 'fgb'``, which the constraint rejected,
  so every FlatGeobuf upload would have failed at dataset creation — the last
  step of the ingest pipeline, after ogr2ogr had already loaded the table.
- ``.kmz`` normalizes to ``'kml'`` and a zipped ``.gdb`` derives ``'fgdb'``.
  Both values were already in the list (unreachable until now, since neither
  extension was an accepted upload), so neither needs a migration.

Hand-written, not autogenerated: autogenerate against a database carrying the
enterprise overlay emits that overlay's SAML columns as core DDL.

Revision ID: 0053_source_format_fgb
Revises: 0052_record_embedding_config_fingerprint
Create Date: 2026-08-26
"""

from typing import Sequence, Union

from alembic import op

revision: str = "0053_source_format_fgb"
down_revision: Union[str, None] = "0052_record_embedding_config_fingerprint"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_BASE_FORMATS = (
    "'geojson', 'shapefile', 'shp', 'gpkg', 'csv', 'kml', 'gml', "
    "'wfs', 'arcgis_featureserver', 'fgdb', 'created', 'geotiff', "
    "'ogcapi_features', 'stac', 'parquet', 'json', 'xlsx', 'xls'"
)
_NEW_FORMATS = "'fgb'"


def upgrade() -> None:
    op.drop_constraint(
        "chk_datasets_source_format", "datasets", schema="catalog", type_="check"
    )
    op.create_check_constraint(
        "chk_datasets_source_format",
        "datasets",
        f"source_format IS NULL OR source_format IN ({_BASE_FORMATS}, {_NEW_FORMATS})",
        schema="catalog",
    )


def downgrade() -> None:
    # Fails loudly if rows with the new formats exist — remove or remap them
    # before downgrading rather than silently orphaning constraint-violating rows.
    op.drop_constraint(
        "chk_datasets_source_format", "datasets", schema="catalog", type_="check"
    )
    op.create_check_constraint(
        "chk_datasets_source_format",
        "datasets",
        f"source_format IS NULL OR source_format IN ({_BASE_FORMATS})",
        schema="catalog",
    )
