"""Allow 'tiles3d_dataset' records and '3dtiles' source formats.

A 3D Tiles tileset is a dataset of its own record type. Its capability row in
``app/core/record_types.py`` is closed, so every feature, OGC, tile and map
path refuses it until the endpoints that serve tilesets exist.

Hand-written, not autogenerated: autogenerate against a database carrying the
enterprise overlay emits that overlay's SAML columns as core DDL.

Revision ID: 0065_tiles3d_record_type
Revises: 0064_scheduled_refresh
Create Date: 2026-09-24
"""

from typing import Sequence, Union

from alembic import op

revision: str = "0065_tiles3d_record_type"
down_revision: Union[str, None] = "0064_scheduled_refresh"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_BASE_RECORD_TYPES = (
    "'vector_dataset', 'raster_dataset', 'vrt_dataset', 'map', 'service', "
    "'collection', 'table'"
)
_NEW_RECORD_TYPES = "'tiles3d_dataset'"

_BASE_FORMATS = (
    "'geojson', 'shapefile', 'shp', 'gpkg', 'csv', 'kml', 'gml', "
    "'wfs', 'arcgis_featureserver', 'fgdb', 'created', 'geotiff', "
    "'ogcapi_features', 'stac', 'parquet', 'json', 'xlsx', 'xls', 'fgb'"
)
_NEW_FORMATS = "'3dtiles'"


def _replace_constraints(record_types: str, formats: str) -> None:
    op.drop_constraint(
        "chk_records_record_type", "records", schema="catalog", type_="check"
    )
    op.create_check_constraint(
        "chk_records_record_type",
        "records",
        f"record_type IN ({record_types})",
        schema="catalog",
    )
    op.drop_constraint(
        "chk_datasets_source_format", "datasets", schema="catalog", type_="check"
    )
    op.create_check_constraint(
        "chk_datasets_source_format",
        "datasets",
        f"source_format IS NULL OR source_format IN ({formats})",
        schema="catalog",
    )


def upgrade() -> None:
    _replace_constraints(
        f"{_BASE_RECORD_TYPES}, {_NEW_RECORD_TYPES}", f"{_BASE_FORMATS}, {_NEW_FORMATS}"
    )


def downgrade() -> None:
    # Fails loudly while any row uses a new value: remove or remap those rows
    # before downgrading rather than leave rows that violate the constraints.
    _replace_constraints(_BASE_RECORD_TYPES, _BASE_FORMATS)
