"""Roll the tile version of every dataset with a timestamptz column.

Vector tiles now write timestamptz properties as UTC text instead of the
database session's local form. Tile cache keys and tile URLs carry
``tile_cache_version``, so rolling it keeps the tile cache, browsers and
CDNs from serving the old text after an upgrade. Datasets without such a
column tile the same bytes and keep their version.

Hand-written, not autogenerated: a data update has nothing to autogenerate.

Revision ID: 0080_timestamptz_tile_text_utc
Revises: 0079_dataset_data_revision
Create Date: 2026-10-08
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0080_timestamptz_tile_text_utc"
down_revision: Union[str, None] = "0079_dataset_data_revision"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_LOCK_TIMEOUT = "SET LOCAL lock_timeout = '5s'"


def upgrade() -> None:
    op.execute(_LOCK_TIMEOUT)
    op.execute(
        sa.text(
            "UPDATE catalog.datasets "
            "SET tile_cache_version = coalesce(tile_cache_version, 1) + 1 "
            "WHERE column_info @> "
            """'[{"type": "timestamp with time zone"}]'::jsonb"""
        )
    )


def downgrade() -> None:
    # A version only moves forward; an older build reads the rolled value.
    pass
