"""Mark admin-entered account emails as verified.

Single sign-on now links an identity by email only to an account whose own
address is verified. Accounts an admin creates are marked verified from now
on; this backfills the ones created before. A local account that is not
pending and has no ``user.register`` audit row is taken as admin-created.
A self-registration whose audit row retention already removed is marked
too, which keeps the linking it had before. Self-registered accounts keep
their state and link once their owner verifies the address.
OAuth-provisioned accounts are left alone: their next sign-in through
their own provider verifies them.

Hand-written, not autogenerated: a data update has nothing to autogenerate.

Revision ID: 0081_admin_entered_email_verified
Revises: 0080_timestamptz_tile_text_utc
Create Date: 2026-10-09
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0081_admin_entered_email_verified"
down_revision: Union[str, None] = "0080_timestamptz_tile_text_utc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("SET LOCAL lock_timeout = '5s'")
    op.execute(
        sa.text(
            "UPDATE catalog.users AS u SET email_verified = true "
            "WHERE u.email_verified = false "
            "AND u.email IS NOT NULL "
            "AND u.auth_provider = 'local' "
            "AND u.status <> 'pending' "
            "AND NOT EXISTS ("
            "SELECT 1 FROM catalog.audit_logs AS a "
            "WHERE a.action = 'user.register' AND a.resource_id = u.id)"
        )
    )


def downgrade() -> None:
    # The older build never reads the flag to link, and the flipped rows
    # can't be told apart from ones whose owner verified them.
    pass
