# SPDX-License-Identifier: Apache-2.0
"""Read-only MCP server for GeoLens.

Hand-maintained — NOT regenerated by `make sdks`. Wraps the GeoLens REST API
(via the generated `geolens` SDK for auth/transport) as Model Context Protocol
tools so coding agents can discover datasets, inspect schemas, and ask spatial
questions against any GeoLens instance.
"""

from __future__ import annotations

from importlib.metadata import PackageNotFoundError, version

__all__ = ["__version__"]

try:
    __version__ = version("geolens-mcp")
except PackageNotFoundError:  # source checkout without installed metadata
    __version__ = "0+unknown"
