# SPDX-License-Identifier: Apache-2.0
"""Config + thin read-only HTTP client for the GeoLens MCP server.

Hand-maintained — NOT regenerated by `make sdks`.

Auth/transport is delegated to the generated ``geolens`` SDK's ``GeolensClient``
(it sends the correct ``X-Api-Key`` / ``Authorization: Bearer`` header and knows
the ``/api`` base-path contract). The tools then call REST paths directly and
return raw JSON — the agent consumes JSON, so the SDK's typed models buy nothing
here and would couple this package to regenerated symbol names.

Configuration (env, mirroring the CLI's ``GEOLENS_*`` names):
    GEOLENS_INSTANCE   Base URL of the instance. ``/api`` is auto-appended when
                       missing (same footgun-guard as ``geolens login``).
    GEOLENS_API_KEY    API key, sent as ``X-Api-Key`` (preferred).
    GEOLENS_TOKEN      JWT bearer token (fallback if no API key).
With neither credential the client is anonymous and sees only public data.
"""

from __future__ import annotations

import os
from typing import Any, Optional
from urllib.parse import urlsplit
from uuid import UUID

import httpx

DEFAULT_TIMEOUT = 30.0


class ConfigError(RuntimeError):
    """Raised when required MCP configuration (e.g. GEOLENS_INSTANCE) is absent."""


def _has_api_prefix(url: str) -> bool:
    # Idempotency guard: an `api` path segment anywhere means `/api` is present.
    path = urlsplit(url).path.rstrip("/")
    return bool(path) and "api" in path.split("/")


def normalize_instance_url(url: str) -> str:
    """Canonicalize an instance URL, auto-appending the required ``/api`` prefix.

    Mirrors ``geolens_cli.config.normalize_instance_url`` (kept in sync by hand —
    the CLI is a separate distribution we can't import). The ``/api`` append is
    the single most common quickstart footgun.
    """
    url = url.strip()
    if not url:
        raise ConfigError("GEOLENS_INSTANCE must not be empty")
    if not url.startswith(("http://", "https://")):
        raise ConfigError(
            f"GEOLENS_INSTANCE must use http or https scheme: got {url!r}"
        )
    url = url.rstrip("/")
    if not _has_api_prefix(url):
        url = f"{url}/api"
    return url


def resolve_instance() -> str:
    instance = os.environ.get("GEOLENS_INSTANCE")
    if not instance:
        raise ConfigError(
            "GEOLENS_INSTANCE is not set. Point it at your instance, "
            "e.g. GEOLENS_INSTANCE=https://geolens.example.com"
        )
    return normalize_instance_url(instance)


def build_httpx_client() -> httpx.Client:
    """Build an httpx.Client authed for the configured instance via the SDK."""
    base_url = resolve_instance()
    api_key = os.environ.get("GEOLENS_API_KEY")
    token = os.environ.get("GEOLENS_TOKEN")

    from geolens import GeolensClient

    if api_key:
        sdk = GeolensClient(base_url, api_key=api_key)
    elif token:
        sdk = GeolensClient(base_url, bearer_token=token)
    else:
        sdk = GeolensClient(base_url)  # anonymous — public data only
    return sdk.client.get_httpx_client()


def _params(**kwargs: Any) -> dict[str, Any]:
    """Drop None-valued query params (httpx would otherwise serialize them)."""
    return {k: v for k, v in kwargs.items() if v is not None}


def _datasets_only(fc: Any) -> Any:
    """Drop catalog-collection features from a ``/search/datasets`` response.

    The endpoint augments page 0 of a text search with up to five ``collection``
    records. This tool advertises every returned feature ``id`` as a dataset id,
    and a collection id 404s in ``get_dataset_schema`` / ``get_features``, so
    strip collections and keep the ``numberReturned`` count consistent. All
    dataset kinds (vector/raster/vrt) are retained — only ``collection`` goes.
    """
    if not isinstance(fc, dict):
        return fc
    feats = fc.get("features")
    if not isinstance(feats, list):
        return fc
    kept = [
        f
        for f in feats
        if not (
            isinstance(f, dict)
            and (f.get("properties") or {}).get("record_type") == "collection"
        )
    ]
    if len(kept) == len(feats):
        return fc
    out = {**fc, "features": kept}
    if isinstance(out.get("numberReturned"), int):
        out["numberReturned"] = len(kept)
    return out


def _id_segment(value: str) -> str:
    """Validate a path-parameter id as a UUID and return its canonical string.

    All three detail routes take ``uuid.UUID`` path params, so the backend only
    ever accepts UUIDs here. MCP tool args are model-controlled, and a raw id
    interpolated into a path is a redirection primitive: httpx normalizes it, so
    ``../admin/users`` collapses to ``GET /api/admin/users`` and even a bare
    ``.``/``..`` turns a detail call into a different authenticated endpoint.
    Parsing as a UUID rejects all of these with a clear error and yields a
    segment with no ``/`` or ``.`` to normalize.
    """
    try:
        return str(UUID(str(value)))
    except (ValueError, AttributeError, TypeError) as exc:
        raise ValueError(f"Invalid id (expected a UUID): {value!r}") from exc


class GeoLensReadOnlyAPI:
    """Read-only calls against a GeoLens instance.

    Holds a configured ``httpx.Client``; tests inject one backed by a
    ``MockTransport``. Paths are relative to the client's ``/api`` base URL.
    Trailing slashes are load-bearing (the API runs ``redirect_slashes=False``):
    the two ``/{id}`` detail routes must have NO trailing slash.
    """

    def __init__(self, http: httpx.Client) -> None:
        self._http = http

    def _get(self, path: str, params: Optional[dict[str, Any]] = None) -> Any:
        try:
            resp = self._http.get(path, params=params or {}, timeout=DEFAULT_TIMEOUT)
            resp.raise_for_status()
        except httpx.HTTPStatusError as exc:
            detail = ""
            try:
                body = exc.response.json()
                detail = body.get("detail") or body.get("message") or ""
            except Exception:
                detail = (exc.response.text or "")[:200]
            raise RuntimeError(
                f"GeoLens API {exc.response.status_code} for {path}"
                + (f": {detail}" if detail else "")
            ) from exc
        except httpx.HTTPError as exc:
            raise RuntimeError(f"Could not reach GeoLens API at {path}: {exc}") from exc
        return resp.json()

    def search_datasets(self, query: str, limit: int = 10, offset: int = 0) -> Any:
        # /search/datasets augments page 0 with up to 5 collection records; drop
        # them so every returned id is usable by the dataset tools.
        return _datasets_only(
            self._get("/search/datasets", _params(q=query, limit=limit, offset=offset))
        )

    def get_dataset_schema(self, dataset_id: str) -> Any:
        # No trailing-slash sibling on this route — must omit it.
        return self._get(f"/datasets/{_id_segment(dataset_id)}")

    def get_features(
        self,
        dataset_id: str,
        limit: int = 10,
        offset: int = 0,
        bbox: Optional[str] = None,
    ) -> Any:
        return self._get(
            f"/collections/{_id_segment(dataset_id)}/items",
            _params(limit=limit, offset=offset, bbox=bbox),
        )

    def list_maps(
        self, search: Optional[str] = None, limit: int = 50, offset: int = 0
    ) -> Any:
        # This endpoint pages with `skip`, not `offset`.
        return self._get("/maps", _params(search=search, limit=limit, skip=offset))

    def get_map(self, map_id: str) -> Any:
        # No trailing-slash sibling on this route — must omit it.
        return self._get(f"/maps/{_id_segment(map_id)}")
