# SPDX-License-Identifier: Apache-2.0
"""Read-only GeoLens MCP server (stdio).

Hand-maintained — NOT regenerated by `make sdks`. Exposes catalog discovery,
schema inspection, and feature/map reads as MCP tools so coding agents can work
against any GeoLens instance. See README.md for client configuration.
"""

from __future__ import annotations

from typing import Any, Optional

from mcp.server.fastmcp import FastMCP

from .client import GeoLensReadOnlyAPI, build_httpx_client

mcp = FastMCP("geolens")

_api: Optional[GeoLensReadOnlyAPI] = None


def _get_api() -> GeoLensReadOnlyAPI:
    # Built lazily so importing the module (and listing tools) never requires
    # GEOLENS_INSTANCE to be set — only invoking a tool does.
    global _api
    if _api is None:
        _api = GeoLensReadOnlyAPI(build_httpx_client())
    return _api


@mcp.tool()
def search_datasets(query: str, limit: int = 10, offset: int = 0) -> Any:
    """Search the GeoLens catalog for datasets by free text.

    Matches title, description, and keywords (semantic ranking is used
    automatically when the instance has it enabled). Returns a GeoJSON
    FeatureCollection where each feature is a dataset record; use the feature
    `id` as the dataset_id for the other tools. Each feature's properties include
    `source_origin` (upload, postgis, service, stac, created, or null) and
    `source_freshness` (fresh, due, overdue, or unknown). Freshness is advisory:
    `due` means one declared update interval has elapsed, while `overdue` means
    two have elapsed; neither proves that the content is wrong.

    Search does not make a detail request per result. When the catalog summary
    has no health/check/refresh value, `source_health`, `source_health_detail`,
    `last_checked_at`, and `last_refreshed_at` are null. Call
    `get_dataset_schema` for populated trust metadata. Raw provider URLs and
    credentials are never included in these source-state fields.

    Args:
        query: Search text.
        limit: Max results (1-200, default 10).
        offset: Result offset for paging.
    """
    return _get_api().search_datasets(query, limit=limit, offset=offset)


@mcp.tool()
def get_dataset_schema(dataset_id: str) -> Any:
    """Get a dataset's schema and source trust metadata.

    Returns columns (name/type/role), geometry type, CRS/SRID, feature count,
    spatial extent, and the safe `source_origin`. `source_health` is healthy,
    missing, inaccessible, or unknown: inaccessible means GeoLens could not
    determine whether the source still exists, while unknown means it was never
    probed or cannot be probed. `source_health_detail` is a fixed GeoLens reason
    code, not provider text. `last_checked_at` records the latest probe attempt;
    `last_refreshed_at` records only the latest successful committed refresh.
    `source_freshness` is advisory; overdue means two declared update intervals
    elapsed without a successful refresh. Raw provider URLs, origin pointers,
    and credentials are excluded. Call this before writing spatial questions so
    you know both the available columns and whether the source may be stale.

    Args:
        dataset_id: Dataset id (e.g. from search_datasets).
    """
    return _get_api().get_dataset_schema(dataset_id)


@mcp.tool()
def get_features(
    dataset_id: str,
    limit: int = 10,
    offset: int = 0,
    bbox: Optional[str] = None,
) -> Any:
    """Get GeoJSON features for a dataset (bounded).

    Returns an OGC-API FeatureCollection. Raster datasets have no features and
    will error. Results are capped by `limit`; page with `offset`.

    Args:
        dataset_id: Dataset id.
        limit: Max features (1-200, default 10).
        offset: Feature offset for paging.
        bbox: Optional bounding box filter "minx,miny,maxx,maxy" (WGS84).
    """
    return _get_api().get_features(dataset_id, limit=limit, offset=offset, bbox=bbox)


@mcp.tool()
def list_maps(search: Optional[str] = None, limit: int = 50, offset: int = 0) -> Any:
    """List saved maps (read-only metadata: id, name, visibility, layer count).

    Args:
        search: Optional text filter on map name/description.
        limit: Max results (1-200, default 50).
        offset: Result offset for paging.
    """
    return _get_api().list_maps(search=search, limit=limit, offset=offset)


@mcp.tool()
def get_map(map_id: str) -> Any:
    """Get one saved map's full metadata, including its layers, view state,
    basemap, and terrain configuration.

    Args:
        map_id: Map id (e.g. from list_maps).
    """
    return _get_api().get_map(map_id)


def main() -> None:
    """Console-script entry point: run the server over stdio."""
    mcp.run()


if __name__ == "__main__":
    main()
