# SPDX-License-Identifier: Apache-2.0
"""Read-only GeoLens MCP server (stdio).

Hand-maintained — NOT regenerated by `make sdks`. Exposes catalog discovery,
schema inspection, and feature/map reads as MCP tools so coding agents can work
against any GeoLens instance. See README.md for client configuration.
"""

from __future__ import annotations

from typing import Any, Optional

from mcp.server.fastmcp import FastMCP

from .client import GeoLensReadOnlyAPI, build_httpx_client

mcp = FastMCP("geolens")

_api: Optional[GeoLensReadOnlyAPI] = None


def _get_api() -> GeoLensReadOnlyAPI:
    # Built lazily so importing the module (and listing tools) never requires
    # GEOLENS_INSTANCE to be set — only invoking a tool does.
    global _api
    if _api is None:
        _api = GeoLensReadOnlyAPI(build_httpx_client())
    return _api


@mcp.tool()
def search_datasets(query: str, limit: int = 10, offset: int = 0) -> Any:
    """Search the GeoLens catalog for datasets by free text.

    Matches title, description, and keywords (semantic ranking is used
    automatically when the instance has it enabled). Returns a GeoJSON
    FeatureCollection where each feature is a dataset record; use the feature
    `id` as the dataset_id for the other tools.

    Args:
        query: Search text.
        limit: Max results (1-200, default 10).
        offset: Result offset for paging.
    """
    return _get_api().search_datasets(query, limit=limit, offset=offset)


@mcp.tool()
def get_dataset_schema(dataset_id: str) -> Any:
    """Get a dataset's schema: columns (name/type/role), geometry type, CRS/SRID,
    feature count, and spatial extent. Call this before writing spatial questions
    so you know the available columns and geometry.

    Args:
        dataset_id: Dataset id (e.g. from search_datasets).
    """
    return _get_api().get_dataset_schema(dataset_id)


@mcp.tool()
def get_features(
    dataset_id: str,
    limit: int = 10,
    offset: int = 0,
    bbox: Optional[str] = None,
) -> Any:
    """Get GeoJSON features for a dataset (bounded).

    Returns an OGC-API FeatureCollection. Raster datasets have no features and
    will error. Results are capped by `limit`; page with `offset`.

    Args:
        dataset_id: Dataset id.
        limit: Max features (1-200, default 10).
        offset: Feature offset for paging.
        bbox: Optional bounding box filter "minx,miny,maxx,maxy" (WGS84).
    """
    return _get_api().get_features(dataset_id, limit=limit, offset=offset, bbox=bbox)


@mcp.tool()
def list_maps(search: Optional[str] = None, limit: int = 50, offset: int = 0) -> Any:
    """List saved maps (read-only metadata: id, name, visibility, layer count).

    Args:
        search: Optional text filter on map name/description.
        limit: Max results (1-200, default 50).
        offset: Result offset for paging.
    """
    return _get_api().list_maps(search=search, limit=limit, offset=offset)


@mcp.tool()
def get_map(map_id: str) -> Any:
    """Get one saved map's full metadata, including its layers, view state,
    basemap, and terrain configuration.

    Args:
        map_id: Map id (e.g. from list_maps).
    """
    return _get_api().get_map(map_id)


def main() -> None:
    """Console-script entry point: run the server over stdio."""
    mcp.run()


if __name__ == "__main__":
    main()
