#!/usr/bin/env bash
# Phase 1061 SEC-S06: generate per-deploy random credentials for the demo
# overlay. Writes .env.demo (gitignored). Refuses to overwrite without --force.
#
# Usage:
#   scripts/init-demo-env.sh           # write fresh .env.demo (refuses if file exists)
#   scripts/init-demo-env.sh --force   # overwrite existing .env.demo
#
# Then start the stack:
#   docker compose -f docker-compose.yml -f docker-compose.demo.yml --env-file .env.demo up -d
set -euo pipefail

FORCE=false
if [[ "${1:-}" == "--force" ]]; then
  FORCE=true
fi

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TARGET="$ROOT/.env.demo"

if [[ -f "$TARGET" && "$FORCE" != "true" ]]; then
  echo "Error: $TARGET already exists. Pass --force to overwrite." >&2
  exit 1
fi

command -v openssl >/dev/null 2>&1 || {
  echo "Error: openssl not found on PATH (required for credential generation)." >&2
  exit 1
}

# Generate random URL-safe strings of the requested byte length.
# openssl rand -base64 N produces ceil(N*4/3) chars; strip newlines and
# padding/separator chars that break env-file parsing.
gen() {
  local bytes=$1
  openssl rand -base64 "$bytes" | tr -d '\n=+/'
}

JWT=$(gen 48)
PG=$(gen 24)
ADM=$(gen 18)
MINIO_USER=$(gen 12)
MINIO_PASS=$(gen 24)

TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

cat > "$TMP" <<EOF
# Generated by scripts/init-demo-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Per-deploy random credentials — DO NOT COMMIT (covered by .gitignore).
# These values pass validate_demo_credentials_guard because they are NOT the
# known-public literal strings committed in .env.demo.example.

# --- Database ---
POSTGRES_DB=geolens
POSTGRES_USER=geolens
POSTGRES_PASSWORD=$PG

# --- Authentication ---
JWT_SECRET_KEY=$JWT
GEOLENS_ADMIN_USERNAME=admin
GEOLENS_ADMIN_PASSWORD=$ADM

# --- Demo opt-in (required by validate_demo_credentials_guard) ---
GEOLENS_DEMO_MODE=true

# --- MinIO (cloud-dev profile only) ---
MINIO_ROOT_USER=$MINIO_USER
MINIO_ROOT_PASSWORD=$MINIO_PASS

# --- Logging ---
LOG_JSON=true
LOG_LEVEL=INFO

# --- Upload (reduced for demo safety) ---
UPLOAD_MAX_SIZE_MB=50

# --- Host Ports ---
DB_PORT=5432
API_PORT=8000
FRONTEND_PORT=8080

# --- Demo Reset ---
RESET_INTERVAL_HOURS=24
EOF

mv "$TMP" "$TARGET"
chmod 600 "$TARGET"

echo "Generated $TARGET"
echo "Admin password (capture this — it is the only output): $ADM"
