# SPDX-License-Identifier: Apache-2.0
"""Download a raster dataset's COG on any storage backend.

Hand-maintained — NOT regenerated by `make sdks`, which cp-stashes it across
regenerations; the drift gate excludes it like ``auth.py``.

Local storage answers the download with the file. Remote assets answer 302
with the file's URL, which the generated ``sync()`` returns as None, and S3
storage may too when the server has presigned downloads enabled; otherwise it
streams the file.
Following that redirect on the GeoLens client would send ``X-API-Key``, cookies
and any other configured header to the storage host (httpx strips only
``Authorization``), so the target is fetched with a separate client that has
none of them. Only ``Range`` and the ``If-*`` precondition headers of the
GeoLens request go along. A Location that isn't an http(s) URL raises
ValueError. A redirect from the storage host is followed only while it stays
on that host and port (http may become https, never the reverse), at most
five times; any other raises ``errors.UnexpectedStatus``.
A 304 answering an ``If-None-Match`` or ``If-Modified-Since`` read of the
target returns None, as the generated call's 304 does; any other failed fetch
of it raises ``errors.UnexpectedStatus``.

The file is streamed into a ``tempfile.SpooledTemporaryFile``, kept in memory
up to ``SPOOL_MAX_SIZE`` bytes and on disk beyond, so a multi-GB COG is never
held in memory. The returned ``File``'s payload is that file, positioned at
the start; close it when done.

Example:
    >>> from geolens import GeolensClient, cog_download
    >>> c = GeolensClient(base_url="https://geolens.example.com/api", api_key="...")
    >>> cog = cog_download.sync(dataset_id, client=c.client)
    >>> data = cog.payload.read()
"""

from __future__ import annotations

import tempfile
from types import ModuleType
from typing import TYPE_CHECKING, Any
from uuid import UUID

import httpx

from . import errors
from .client import AuthenticatedClient, Client
from .types import File

if TYPE_CHECKING:
    from .models.problem_detail import ProblemDetail

__all__ = ["SPOOL_MAX_SIZE", "asyncio", "sync"]

SPOOL_MAX_SIZE = 4 * 1024 * 1024
_MAX_STORAGE_REDIRECTS = 5
_REDIRECT_STATUSES = frozenset({301, 302, 303, 307, 308})

# Not credentials, and a ranged or conditional read needs them at the storage
# host the backend redirects to.
_FORWARDED_HEADERS = (
    "range",
    "if-range",
    "if-match",
    "if-none-match",
    "if-modified-since",
    "if-unmodified-since",
)


def sync(
    dataset_id: UUID,
    *,
    client: AuthenticatedClient | Client,
) -> File | ProblemDetail | None:
    """Like the generated ``sync()``, but a 302 returns the target's bytes."""
    operation = _operation()
    with client.get_httpx_client().stream(
        **operation._get_kwargs(dataset_id=dataset_id), follow_redirects=False
    ) as response:
        if response.status_code in (200, 206):
            return _file(response)
        if response.status_code != 302:
            response.read()
            return operation._parse_response(client=client, response=response)
        target, headers = _redirect_url(response), _forwarded(response)
    with httpx.Client(**_storage_client_args(client)) as storage:
        for _ in range(_MAX_STORAGE_REDIRECTS + 1):
            with storage.stream("GET", target, headers=headers) as fetched:
                hop = _next_hop(fetched, target)
                if hop is None:
                    return _file(fetched)
            target = hop
    raise _too_many_redirects(fetched)


async def asyncio(
    dataset_id: UUID,
    *,
    client: AuthenticatedClient | Client,
) -> File | ProblemDetail | None:
    """Like the generated ``asyncio()``, but a 302 returns the target's bytes."""
    operation = _operation()
    async with client.get_async_httpx_client().stream(
        **operation._get_kwargs(dataset_id=dataset_id), follow_redirects=False
    ) as response:
        if response.status_code in (200, 206):
            return await _afile(response)
        if response.status_code != 302:
            await response.aread()
            return operation._parse_response(client=client, response=response)
        target, headers = _redirect_url(response), _forwarded(response)
    async with httpx.AsyncClient(**_storage_client_args(client)) as storage:
        for _ in range(_MAX_STORAGE_REDIRECTS + 1):
            async with storage.stream("GET", target, headers=headers) as fetched:
                hop = _next_hop(fetched, target)
                if hop is None:
                    return await _afile(fetched)
            target = hop
    raise _too_many_redirects(fetched)


def _operation() -> ModuleType:
    # Imported on call: the generated module loads every model, and
    # `import geolens` shouldn't pay for that.
    from .api.datasets_export import download_cog_datasets_dataset_id_download_cog_get

    return download_cog_datasets_dataset_id_download_cog_get


def _storage_client_args(client: AuthenticatedClient | Client) -> dict[str, Any]:
    # A custom CA bundle or timeout usually applies to the storage host too,
    # and neither is a credential.
    return {"verify": client._verify_ssl, "timeout": client._timeout}


def _redirect_url(response: httpx.Response) -> httpx.URL:
    location = response.headers.get("location")
    if not location:
        raise ValueError("The COG download answered 302 without a Location header")
    url = response.url.join(location)
    # The URL stays out of the message: a presigned URL is a credential.
    if url.scheme not in ("http", "https") or not url.host:
        raise ValueError(
            "The COG download redirected to an unsupported URL: expected http(s) "
            f"with a host, got scheme {url.scheme!r}"
        )
    return url


def _next_hop(response: httpx.Response, current: httpx.URL) -> httpx.URL | None:
    """Where a storage redirect leads, or None when the response is the answer."""
    if (
        response.status_code not in _REDIRECT_STATUSES
        or "location" not in response.headers
    ):
        return None
    target = current.join(response.headers["location"])
    # Only the first URL was validated by the server; a storage host must not
    # bounce the download to a different host.
    upgrade = (current.scheme, target.scheme) == ("http", "https")
    if (
        target.host != current.host
        or target.port != current.port
        or (target.scheme != current.scheme and not upgrade)
    ):
        raise errors.UnexpectedStatus(
            response.status_code,
            f"Storage redirected off {current.host} to {target.host}".encode(),
        )
    return target


def _too_many_redirects(response: httpx.Response) -> errors.UnexpectedStatus:
    return errors.UnexpectedStatus(
        response.status_code,
        f"More than {_MAX_STORAGE_REDIRECTS} storage redirects".encode(),
    )


def _forwarded(response: httpx.Response) -> dict[str, str]:
    sent = response.request.headers
    return {name: sent[name] for name in _FORWARDED_HEADERS if name in sent}


def _not_modified(response: httpx.Response) -> bool:
    sent = response.request.headers
    return response.status_code == 304 and (
        "if-none-match" in sent or "if-modified-since" in sent
    )


def _file(response: httpx.Response) -> File | None:
    if _not_modified(response):
        return None
    if not response.is_success:
        raise errors.UnexpectedStatus(response.status_code, response.read())
    payload = tempfile.SpooledTemporaryFile(max_size=SPOOL_MAX_SIZE)
    for chunk in response.iter_bytes():
        payload.write(chunk)
    payload.seek(0)
    return File(payload=payload)


async def _afile(response: httpx.Response) -> File | None:
    if _not_modified(response):
        return None
    if not response.is_success:
        raise errors.UnexpectedStatus(response.status_code, await response.aread())
    payload = tempfile.SpooledTemporaryFile(max_size=SPOOL_MAX_SIZE)
    async for chunk in response.aiter_bytes():
        payload.write(chunk)
    payload.seek(0)
    return File(payload=payload)
