# SPDX-License-Identifier: Apache-2.0
"""Download a raster dataset's COG on any storage backend.

Hand-maintained — NOT regenerated by `make sdks`, which cp-stashes it across
regenerations; the drift gate excludes it like ``auth.py``.

Local storage answers the download with the file. S3 storage and remote assets
answer 302 with the file's URL, which the generated ``sync()`` returns as None.
Following that redirect on the GeoLens client would send ``X-API-Key``, cookies
and any other configured header to the storage host (httpx strips only
``Authorization``), so the target is fetched with a separate client that has
none of them. Only ``Range`` and the ``If-*`` precondition headers of the
GeoLens request go along. A Location that isn't an http(s) URL raises
ValueError. A 304 answering an ``If-None-Match`` or ``If-Modified-Since`` read
of the target returns None, as the generated call's 304 does; any other failed
fetch of it raises ``errors.UnexpectedStatus``.

Example:
    >>> from geolens import GeolensClient, cog_download
    >>> c = GeolensClient(base_url="https://geolens.example.com/api", api_key="...")
    >>> cog = cog_download.sync(dataset_id, client=c.client)
    >>> data = cog.payload.read()
"""

from __future__ import annotations

from io import BytesIO
from types import ModuleType
from typing import TYPE_CHECKING, Any
from uuid import UUID

import httpx

from . import errors
from .client import AuthenticatedClient, Client
from .types import File

if TYPE_CHECKING:
    from .models.problem_detail import ProblemDetail

__all__ = ["asyncio", "sync"]

# Not credentials, and a ranged or conditional read needs them at the storage
# host the backend redirects to.
_FORWARDED_HEADERS = (
    "range",
    "if-range",
    "if-match",
    "if-none-match",
    "if-modified-since",
    "if-unmodified-since",
)


def sync(
    dataset_id: UUID,
    *,
    client: AuthenticatedClient | Client,
) -> File | ProblemDetail | None:
    """Like the generated ``sync()``, but a 302 returns the target's bytes."""
    operation = _operation()
    response = client.get_httpx_client().request(
        **operation._get_kwargs(dataset_id=dataset_id), follow_redirects=False
    )
    if response.status_code != 302:
        return operation._parse_response(client=client, response=response)
    with httpx.Client(**_storage_client_args(client)) as storage:
        return _file(storage.get(_redirect_url(response), headers=_forwarded(response)))


async def asyncio(
    dataset_id: UUID,
    *,
    client: AuthenticatedClient | Client,
) -> File | ProblemDetail | None:
    """Like the generated ``asyncio()``, but a 302 returns the target's bytes."""
    operation = _operation()
    response = await client.get_async_httpx_client().request(
        **operation._get_kwargs(dataset_id=dataset_id), follow_redirects=False
    )
    if response.status_code != 302:
        return operation._parse_response(client=client, response=response)
    async with httpx.AsyncClient(**_storage_client_args(client)) as storage:
        return _file(
            await storage.get(_redirect_url(response), headers=_forwarded(response))
        )


def _operation() -> ModuleType:
    # Imported on call: the generated module loads every model, and
    # `import geolens` shouldn't pay for that.
    from .api.datasets_export import download_cog_datasets_dataset_id_download_cog_get

    return download_cog_datasets_dataset_id_download_cog_get


def _storage_client_args(client: AuthenticatedClient | Client) -> dict[str, Any]:
    # A custom CA bundle or timeout usually applies to the storage host too,
    # and neither is a credential.
    return {
        "verify": client._verify_ssl,
        "timeout": client._timeout,
        "follow_redirects": True,
    }


def _redirect_url(response: httpx.Response) -> httpx.URL:
    location = response.headers.get("location")
    if not location:
        raise ValueError("The COG download answered 302 without a Location header")
    url = response.url.join(location)
    # The URL stays out of the message: a presigned URL is a credential.
    if url.scheme not in ("http", "https") or not url.host:
        raise ValueError(
            "The COG download redirected to an unsupported URL: expected http(s) "
            f"with a host, got scheme {url.scheme!r}"
        )
    return url


def _forwarded(response: httpx.Response) -> dict[str, str]:
    sent = response.request.headers
    return {name: sent[name] for name in _FORWARDED_HEADERS if name in sent}


def _file(response: httpx.Response) -> File | None:
    sent = response.request.headers
    if response.status_code == 304 and (
        "if-none-match" in sent or "if-modified-since" in sent
    ):
        return None
    if not response.is_success:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    return File(payload=BytesIO(response.content))
