# SPDX-License-Identifier: Apache-2.0
"""Minimal `geolens.yaml` manifest template helpers."""

from __future__ import annotations

from pathlib import Path


def minimal_manifest_text() -> str:
    """Return a deterministic starter manifest that validates as v1."""

    return """manifest_version: "1"
catalog:
  title: Example GeoLens catalog
  description: Starter catalog generated by `geolens init`.
  organization: Example Organization
datasets:
  - key: sample-roads
    title: Sample roads
    description: Replace this entry with your dataset description.
    sources:
      - type: vector
        uri: ./data/roads.geojson
        format: geojson
    metadata:
      tags:
        - example
        - roads
      organization: Example Organization
      crs: EPSG:4326
      license: CC-BY-4.0
      attribution: Example Organization
      bbox: [-74.1, 40.5, -73.7, 40.9]
    publication:
      intent: draft
"""


def write_minimal_manifest(path: Path, *, force: bool = False) -> Path:
    """Write the starter manifest, refusing existing files unless forced."""

    if path.exists() and not force:
        raise FileExistsError(path)

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(minimal_manifest_text(), encoding="utf-8")
    return path
